"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm");
const root=path.resolve(__dirname,".."),html=fs.readFileSync(path.join(root,"index.html"),"utf8");
const core=require(path.join(root,"final-core-production.js")),metadata=require(path.join(root,"c4-validation-metadata.js"));
const capitalInput=require(path.join(root,"personal-capital-input-core.js")),capitalPolicy=require(path.join(root,"personal-capital-policy-core.js"));
const formalSymbols=["0050","00662","00757","00830","00935"],formalC4Source={isFormalC4Symbol:symbol=>formalSymbols.includes(symbol)};
const validation=metadata.createResolver({formalC4Source});
const source=(name,next)=>{const start=html.indexOf(`function ${name}(`);assert(start>=0,name);const end=html.indexOf(`function ${next}(`,start);assert(end>start,next);return html.slice(start,end).replace(/\basync\s*$/,"")};
assert.deepEqual(Object.values(metadata.STATUS),["FORMAL","VALIDATING","REFERENCE"]);
for(const symbol of formalSymbols)assert.equal(validation.resolve(symbol).status,"FORMAL",symbol);
for(const symbol of ["00635U","2330","009815","00631L","09999Z","12345A"])assert.equal(validation.resolve(symbol).status,"REFERENCE",symbol);
assert.equal(Object.keys(metadata.VALIDATING_METADATA).length,0,"no active C4-specific validation record has been established");
const validating=metadata.createResolver({formalC4Source,validatingMetadata:{"00878":{status:"VALIDATING",method:"BENCHMARK_VALIDATION",since:"2026-09-25"},"0050":{status:"VALIDATING",method:"FORWARD_SHADOW"},"00635U":{status:"VALIDATING"}}});
assert.equal(validating.resolve("00878").status,"VALIDATING");
assert.equal(validating.resolve("0050").status,"FORMAL","formal C4 scope always wins");
assert.equal(validating.resolve("00635U").status,"REFERENCE","an unsubstantiated validating label must not be promoted");
assert.equal(metadata.createResolver({formalC4Source:{isFormalC4Symbol:symbol=>symbol==="NEWETF"}}).resolve("NEWETF").status,"FORMAL","formal follows the live formal C4 source");
assert.equal(metadata.createResolver({formalC4Source:{isFormalC4Symbol:()=>false}}).resolve("0050").status,"REFERENCE","no duplicated formal list may survive a scope change");
const moduleSource=fs.readFileSync(path.join(root,"c4-validation-metadata.js"),"utf8");
assert.match(moduleSource,/HSFormalCoreScoreAdapter\)\?\.isFormalC4Symbol\?\.\(ticker\)/);
assert.doesNotMatch(moduleSource,/SUPPORTED_TICKERS|buildFinal|buildAdHocScore|final_core_score|LONG_RADAR_SCORED_CODES/);
assert.match(html,/HSFormalCoreScoreAdapter=Object\.freeze\(\{scoreFor:currentFormalCoreScoreForSymbol,isFormalC4Symbol:symbol=>LONG_RADAR_SCORED_CODES\.has/);
const universeSource=html.match(/const LONG_RADAR_CODES=new Set\([^\n]+\);\s*const LONG_RADAR_SCORED_CODES=new Set\([^\n]+\);/)?.[0];
const adapterSource=html.match(/window\.HSFormalCoreScoreAdapter=Object\.freeze\([^\n]+\);/)?.[0];
assert.ok(universeSource&&adapterSource,"production Formal universe and adapter must exist");
const browser={HSFinalCoreProduction:{SUPPORTED_TICKERS:["009815"]}};browser.window=browser;vm.createContext(browser);vm.runInContext(moduleSource,browser);
assert.equal(browser.HSC4ValidationMetadata.resolve("0050").status,"REFERENCE","uninitialized formal C4 scope fails closed");
vm.runInContext(`${universeSource}\nconst currentFormalCoreScoreForSymbol=()=>null;\n${adapterSource}`,browser);
for(const symbol of ["0050","00662","00830","00935"])assert.equal(browser.HSC4ValidationMetadata.resolve(symbol).status,"FORMAL",symbol);
assert.equal(browser.HSC4ValidationMetadata.resolve("009815").status,"REFERENCE","SUPPORTED_TICKERS cannot override Formal eligibility");
for(const symbol of ["00635U","2330"])assert.equal(browser.HSC4ValidationMetadata.resolve(symbol).status,"REFERENCE",symbol);
for(const [symbol,formalC4,coreSupported,capitalEligible] of [["00757",true,true,false],["009815",false,false,true]]){
  assert.equal(browser.HSFormalCoreScoreAdapter.isFormalC4Symbol(symbol),formalC4,`${symbol} formal C4 scope`);
  assert.equal(core.SUPPORTED_TICKERS.includes(symbol),coreSupported,`${symbol} Core builder scope`);
  assert.equal(capitalInput.ELIGIBLE_SYMBOLS.includes(symbol),capitalEligible,`${symbol} capital input scope`);
  assert.equal(capitalPolicy.ELIGIBLE_SYMBOLS.includes(symbol),capitalEligible,`${symbol} capital policy scope`);
}
assert.match(html,/<script src="final-core-production\.js[^\"]*"><\/script>\s*<script src="c4-validation-metadata\.js[^\"]*"><\/script>/);
const blocks=[source("renderWatchAdHocResult","queryWatchAdHoc"),source("watchDiagnosticCard","renderWatchDiagnostics"),source("openWatchDiagnostic","closeWatchDiagnostic")];
for(const block of blocks)assert.match(block,/window\.HSC4ValidationMetadata\.resolve\(/,"each view must use the single resolver");
assert.doesNotMatch(html,/function watchValidationStatus\(|function watchValidationInfo\(/);
const nodes=new Map(),node=id=>{if(!nodes.has(id))nodes.set(id,{innerHTML:"",textContent:"",classList:{add(){}},setAttribute(){},focus(){},querySelector(){return null}});return nodes.get(id)};
const watchlist=[{id:"00635U",name:"黃金ETF"},{id:"2330",name:"台積電"}];
const context={window:{HSC4ValidationMetadata:validation},HSFinalCoreProduction:core,currentFormalCoreScoreForSymbol:()=>({available:true,score:39.4,display_score:39,trading_date:"2026-09-24"}),watchlist,watchDiagnosticState:new Map(),$:node,esc:value=>String(value??""),fmt:value=>String(value),signed:value=>String(value),watchDirectionIcon:()=>"→",watchMetric:()=>"—",watchDiagnosticSection:(title)=>`<section>${title}</section>`,adHocReasonText:()=>"歷史行情不足，尚無法完整計算 C4。",lastWatchDiagnosticTrigger:null};
vm.createContext(context);
vm.runInContext(source("watchUnavailableState","adHocComponentRow")+"\n"+source("adHocComponentRow","renderWatchAdHocResult")+"\n"+blocks.join("\n"),context);
const score=(ticker)=>({available:true,ticker,name:ticker,score:23.4,displayScore:23,tier:"一般持有",scoreAsOf:"2026-09-24",components:{}});
const diagnostic={price:100,changeValue:null,changePct:null,trend:null,pullback:null,weekly:null,rs:null,recovery:null,dataAsOf:"2026-09-24"};
for(const symbol of ["00635U","2330"]){
  const resolved=validation.resolve(symbol);
  context.renderWatchAdHocResult({kind:"ready",ticker:symbol,score:score(symbol)});
  const quick=node("#watchAdHocResult").innerHTML;
  const watch=context.watchDiagnosticCard({id:symbol,name:symbol},{kind:"ready",diagnostic,adHoc:score(symbol)});
  context.watchDiagnosticState.set(symbol,{kind:"ready",diagnostic,adHoc:score(symbol)});
  context.openWatchDiagnostic(symbol,null);
  const detail=node("#watchDiagnosticContent").innerHTML;
  for(const rendered of [quick,watch,detail])assert.match(rendered,new RegExp(resolved.label));
  assert.match(quick,/HS C4[\s\S]*>23</);assert.match(watch,/HS C4[\s\S]*>23</);assert.match(detail,/HS C4 23/);
}
context.renderWatchAdHocResult({kind:"ready",ticker:"00635U",score:{available:false,reason:"INSUFFICIENT_DAILY_HISTORY"}});
assert.match(node("#watchAdHocResult").innerHTML,/HS C4 暫無分數/);
assert.doesNotMatch(node("#watchAdHocResult").innerHTML,/HS C4 0|驗證中/);
context.currentFormalCoreScoreForSymbol=()=>({available:false,reason:"WAIT_NATIVE"});
for(const [symbol,resolver,label] of [["009815",validation,"參考"],["0050",validation,"正式"],["00878",validating,"驗證中"]]){
  context.window.HSC4ValidationMetadata=resolver;
  const unavailable={available:false,reason:"INSUFFICIENT_DAILY_HISTORY"};
  context.renderWatchAdHocResult({kind:"ready",ticker:symbol,name:symbol,score:unavailable});
  const quick=node("#watchAdHocResult").innerHTML;
  const watch=context.watchDiagnosticCard({id:symbol,name:symbol},{kind:"ready",diagnostic,adHoc:unavailable});
  context.watchlist.push({id:symbol,name:symbol});
  context.watchDiagnosticState.set(symbol,{kind:"ready",diagnostic,adHoc:unavailable});
  context.openWatchDiagnostic(symbol,null);
  const detail=node("#watchDiagnosticContent").innerHTML;
  for(const rendered of [quick,watch,detail]){
    assert.match(rendered,/HS C4 暫無分數/,`${symbol} unavailable calculation state`);
    assert.match(rendered,new RegExp(label),`${symbol} validation status remains visible`);
    assert.doesNotMatch(rendered,/HS C4 0|一般持有|回檔訊號出現|<div class="watchAdHocComponents">/,`${symbol} must not gain a fake score, tier or factors`);
  }
  context.watchlist.pop();
}
context.window.HSC4ValidationMetadata=validation;
context.renderWatchAdHocResult({kind:"ready",ticker:"0050",score:score("0050")});
assert.match(node("#watchAdHocResult").innerHTML,/HS C4 暫無分數[\s\S]*正式/,"canonical unavailable must retain FORMAL badge");
assert.doesNotMatch(node("#watchAdHocResult").innerHTML,/HS C4 0|<div class="watchAdHocComponents">/);
context.currentFormalCoreScoreForSymbol=()=>({available:true,score:39.4,display_score:39,trading_date:"2026-09-24"});
assert.equal(context.watchScoreForDisplay("00830",score("00830")).score,39.4,"validation status cannot replace canonical formal score");
assert.equal(context.watchScoreForDisplay("00830",score("00830")).tier,core.labelFor(39.4).label,"formal status cannot alter canonical tier");
assert.equal(context.watchScoreForDisplay("00635U",score("00635U")).score,23.4,"reference status cannot change the research score");
assert.equal(validating.resolve("00878").status,"VALIDATING");
assert.equal(context.watchScoreForDisplay("00878",score("00878")).score,23.4,"validating status cannot change the research score");
assert.equal(context.watchScoreForDisplay("00878",score("00878")).tier,"一般持有","validating status cannot alter tier");
assert.equal(context.watchScoreForDisplay("00635U",score("00635U")).tier,"一般持有","validation cannot alter tier");
console.log("PASS C4 validation metadata: formal C4 scope, validating fixture, reference fallback, cross-view parity, unavailable guard and score isolation");
