const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm");
const root=path.resolve(__dirname,"..");
const push=require(path.join(root,"radar-push-subscription-v1.js"));
const html=fs.readFileSync(path.join(root,"index.html"),"utf8"),css=fs.readFileSync(path.join(root,"formal-black-gold.css"),"utf8"),swSource=fs.readFileSync(path.join(root,"push-service-worker.js"),"utf8"),clientSource=fs.readFileSync(path.join(root,"radar-push-subscription-v1.js"),"utf8");
function storage(value=null){const data=new Map(value?[[push.PREFERENCES_KEY,JSON.stringify(value)]]:[]);return{getItem:key=>data.get(key)||null,setItem:(key,item)=>data.set(key,item),data}}
function documentMock(){return{baseURI:"https://wl03049329-blip.github.io/-hs-invest/",querySelector:selector=>selector.includes("hs-live-railway-url")?{content:"https://hs-invest-production.up.railway.app/api/live-scores"}:null}}
function NotificationMock(permission="granted"){return class NotificationApi{static permission=permission;static async requestPermission(){return permission}}}
function channelMock(){return class Channel{constructor(){this.port1={onmessage:null};this.port2={peer:this.port1}}}}
function worker(){return{postMessage(message,ports){ports[0].peer.onmessage({data:{type:message.type,version:"HS_PUSH_SW_V2"}})}}}
function subscription(){return{toJSON:()=>({endpoint:"https://fcm.googleapis.com/fcm/send/test",keys:{p256dh:"A".repeat(87),auth:"B".repeat(22)}}),unsubscribe:async()=>true}}
function browser({permission="granted",existing=null,subscribeError=null}={}){const sub=existing;const registration={active:worker(),pushManager:{getSubscription:async()=>sub,subscribe:async()=>{if(subscribeError)throw subscribeError;return subscription()}}};const navigatorObj={serviceWorker:{register:async()=>registration,ready:Promise.resolve(registration),getRegistration:async()=>registration}};const windowObj={navigator:navigatorObj,PushManager:function(){},Notification:NotificationMock(permission),isSecureContext:true,localStorage:storage(),fetch:null};return{windowObj,navigatorObj,registration}}
function ok(data,status=200){return Promise.resolve({ok:status>=200&&status<300,status,json:async()=>data})}
function fetchSequence(...responses){const calls=[];const fn=(...args)=>{calls.push(args);const next=responses.shift();return typeof next==="function"?next(...args):next};fn.calls=calls;return fn}

test("01 runtime marker and versioned asset are present",()=>{assert.match(html,/data-radar-push-phase="11b2c"/);assert.match(html,/20260920-background-alert-cutover-phase11b2c/)});
test("02 background and system notification UI are separate",()=>{assert.match(html,/系統通知/);assert.match(html,/背景通知/);assert.match(html,/Background Web Push/)});
test("03 default preference is opt-out",()=>assert.deepEqual(push.defaults(),{version:1,enabled:false,subscription_id:null,last_sync_at:null,status:"OFF",rules_sync_status:"NOT_SYNCED",rules_version:null}));
test("04 unsupported without secure context",()=>assert.equal(push.capability({windowObj:{PushManager(){},isSecureContext:false,Notification:NotificationMock()},navigatorObj:{serviceWorker:{}}}).supported,false));
test("05 unsupported without service worker",()=>assert.equal(push.capability({windowObj:{PushManager(){},isSecureContext:true,Notification:NotificationMock()},navigatorObj:{}}).supported,false));
test("06 denied state is detected before subscribe",()=>assert.equal(push.capability({windowObj:{PushManager(){},isSecureContext:true,Notification:NotificationMock("denied")},navigatorObj:{serviceWorker:{}}}).permission,"denied"));
test("07 service worker URL respects GitHub Pages base path",()=>assert.equal(push.swUrl(documentMock()),"https://wl03049329-blip.github.io/-hs-invest/push-service-worker.js"));
test("08 service worker scope respects GitHub Pages base path",()=>assert.equal(push.swScope(documentMock()),"https://wl03049329-blip.github.io/-hs-invest/"));
test("09 registration reports exact service worker version",async()=>{const b=browser();assert.equal(await push.workerVersion(b.registration,{MessageChannelApi:channelMock()}),"HS_PUSH_SW_V2")});
test("10 SW version marker is exact",()=>assert.match(swSource,/HS_PUSH_SW_VERSION\s*=\s*"HS_PUSH_SW_V2"/));
test("11 SW has no fetch event handler",()=>assert.doesNotMatch(swSource,/addEventListener\s*\(\s*["']fetch["']/));
test("12 SW uses no Cache API",()=>assert.doesNotMatch(swSource,/\bcaches\b|CacheStorage|precache|workbox/i));
test("13 SW handles only required lifecycle events",()=>{for(const event of ["install","activate","push","notificationclick","pushsubscriptionchange"])assert.match(swSource,new RegExp(`addEventListener\\(\\"${event}\\"`))});
test("14 push handler enforces fixed test type and copy",()=>{assert.match(swSource,/payload\.type === "TEST_PUSH"/);assert.match(swSource,/payload\.title === TEST_TITLE/);assert.match(swSource,/payload\.body === TEST_BODY/)});
test("15 notification tag deduplicates tests",()=>{assert.match(swSource,/"hs-radar-test-push"/);assert.match(swSource,/renotify: false/)});
test("16 test notification is not requireInteraction and not silent",()=>{assert.match(swSource,/requireInteraction: false/);assert.match(swSource,/silent: false/)});
test("17 click route focuses existing client then opens safe scope",()=>{assert.match(swSource,/clients\.matchAll/);assert.match(swSource,/existing\.focus/);assert.match(swSource,/clients\.openWindow\(appUrl\)/);assert.match(swSource,/self\.registration\.scope/)});
test("18 subscription change never performs fake resubscribe",()=>{const handler=swSource.slice(swSource.indexOf('addEventListener("pushsubscriptionchange"'));assert.match(handler,/RE_ENABLE_REQUIRED/);assert.doesNotMatch(handler,/\.subscribe\(/)});
test("19 private VAPID key never appears in frontend or SW",()=>{assert.doesNotMatch(html+clientSource+swSource,/VAPID_PRIVATE_KEY|private_key/)});
test("20 public config endpoint is derived from Railway URL",()=>assert.equal(push.apiBase(documentMock()),"https://hs-invest-production.up.railway.app"));
test("21 storage normalizes invalid local state",()=>assert.equal(push.load(storage({enabled:"yes",status:"fake"})).status,"OFF"));
test("22 enable obtains config, registers, subscribes and persists opaque id",async()=>{const b=browser(),s=storage(),fetchFn=fetchSequence(ok({available:true,public_key:"AQID"}),ok({status:"SUBSCRIBED",subscription_id:"opaque-id"}));const result=await push.enable({windowObj:b.windowObj,navigatorObj:b.navigatorObj,documentObj:documentMock(),NotificationApi:b.windowObj.Notification,storage:s,fetchFn,MessageChannelApi:channelMock(),isSecureContext:true});assert.equal(result.status,"ON");assert.equal(result.subscription_id,"opaque-id");assert.equal(fetchFn.calls.length,2)});
test("23 permission default is requested only inside explicit enable flow",()=>{assert.match(clientSource,/async function enable[\s\S]*requestPermission\(\)/);assert.doesNotMatch(clientSource,/setTimeout\([^)]*requestPermission/)});
test("24 registration failure records connection failure without enabled state",async()=>{const b=browser();b.navigatorObj.serviceWorker.register=async()=>{throw new Error("registration")};const s=storage(),fetchFn=fetchSequence(ok({available:true,public_key:"AQID"}));await assert.rejects(()=>push.enable({windowObj:b.windowObj,navigatorObj:b.navigatorObj,documentObj:documentMock(),NotificationApi:b.windowObj.Notification,storage:s,fetchFn,MessageChannelApi:channelMock(),isSecureContext:true}));assert.equal(push.load(s).status,"CONNECTION_FAILED");assert.equal(push.load(s).enabled,false)});
test("25 backend subscribe failure rolls back newly created browser subscription",async()=>{let unsubscribed=false;const sub=subscription();sub.unsubscribe=async()=>{unsubscribed=true;return true};const b=browser();b.registration.pushManager.subscribe=async()=>sub;const s=storage(),fetchFn=fetchSequence(ok({available:true,public_key:"AQID"}),ok({detail:"down"},503));await assert.rejects(()=>push.enable({windowObj:b.windowObj,navigatorObj:b.navigatorObj,documentObj:documentMock(),NotificationApi:b.windowObj.Notification,storage:s,fetchFn,MessageChannelApi:channelMock(),isSecureContext:true}));assert.equal(unsubscribed,true);assert.equal(push.load(s).status,"CONNECTION_FAILED")});
test("26 duplicate browser subscription is reused",async()=>{const b=browser({existing:subscription()}),fetchFn=fetchSequence(ok({available:true,public_key:"AQID"}),ok({subscription_id:"same"}));b.registration.pushManager.subscribe=async()=>{throw new Error("must not subscribe")};const result=await push.enable({windowObj:b.windowObj,navigatorObj:b.navigatorObj,documentObj:documentMock(),NotificationApi:b.windowObj.Notification,storage:storage(),fetchFn,MessageChannelApi:channelMock(),isSecureContext:true});assert.equal(result.subscription_id,"same")});
test("27 unsubscribe browser then backend while preserving unrelated storage",async()=>{let unsubscribed=false;const sub=subscription();sub.unsubscribe=async()=>{unsubscribed=true;return true};const b=browser({existing:sub}),s=storage({enabled:true,subscription_id:"opaque",status:"ON"});s.setItem("HS_RADAR_ALERT_RULES_V1","preserve");const fetchFn=fetchSequence(ok({status:"UNSUBSCRIBED"}));const result=await push.disable({windowObj:b.windowObj,navigatorObj:b.navigatorObj,documentObj:documentMock(),storage:s,fetchFn});assert.equal(unsubscribed,true);assert.equal(result.status,"OFF");assert.equal(s.getItem("HS_RADAR_ALERT_RULES_V1"),"preserve")});
test("28 browser unsubscribe with server failure records reconciliation state",async()=>{const b=browser({existing:subscription()}),s=storage({enabled:true,subscription_id:"opaque",status:"ON"}),fetchFn=fetchSequence(ok({detail:"down"},503));await assert.rejects(()=>push.disable({windowObj:b.windowObj,navigatorObj:b.navigatorObj,documentObj:documentMock(),storage:s,fetchFn}));assert.equal(push.load(s).status,"SERVER_CLEANUP_REQUIRED")});
test("29 test endpoint receives subscription id only",async()=>{const s=storage({enabled:true,subscription_id:"opaque",status:"ON"}),fetchFn=fetchSequence(ok({status:"SENT"}));await push.testPush({windowObj:{localStorage:s,fetch:fetchFn},documentObj:documentMock(),storage:s,fetchFn});const body=JSON.parse(fetchFn.calls[0][1].body);assert.deepEqual(body,{subscription_id:"opaque"})});
test("30 test button is conditional and no arbitrary message input exists",()=>{assert.match(html,/id="radarPushTest"/);assert.match(html,/status==="ON"/);assert.doesNotMatch(html,/radarPush(Message|Body|Title)/)});
test("31 CSS has touch-safe responsive push controls",()=>{assert.match(css,/\.radarPushSettings \.radarPushActions button\{[^}]*min-width:118px/);assert.match(css,/@media\(max-width:600px\)\{\.radarPushActions\{display:grid;grid-template-columns:1fr;width:100%/)});
test("32 malformed push payload fails soft without notification",async()=>{const events={},notifications=[];const self={addEventListener:(name,fn)=>events[name]=fn,skipWaiting(){},clients:{claim(){},matchAll:async()=>[],openWindow(){}},registration:{scope:"https://example.test/app/",showNotification:(...args)=>notifications.push(args)}};vm.runInNewContext(swSource,{self,URL});events.push({data:{json:()=>({type:"BAD"})},waitUntil(){throw new Error("must not wait")}});assert.equal(notifications.length,0)});
test("33 valid push shows fixed notification while page process is absent",async()=>{const events={},notifications=[];const self={addEventListener:(name,fn)=>events[name]=fn,skipWaiting(){},clients:{claim(){},matchAll:async()=>[],openWindow(){}},registration:{scope:"https://example.test/app/",showNotification:async(...args)=>notifications.push(args)}};vm.runInNewContext(swSource,{self,URL});let promise;events.push({data:{json:()=>({version:"HS_WEB_PUSH_PAYLOAD_V1",type:"TEST_PUSH",title:"HS ETF 雷達",body:"背景通知測試成功",route:"./",sent_at:"2026-09-19T00:00:00Z",notification_id:"test"})},waitUntil:value=>promise=value});await promise;assert.equal(notifications.length,1);assert.equal(notifications[0][0],"HS ETF 雷達")});
