const assert=require("assert"),ledger=require("../portfolio-ledger-core.js"),workflow=require("../portfolio-workflow-core.js"),resilience=require("../portfolio-resilience-core.js");let passed=0;
const ok=(name,fn)=>{fn();passed++;console.log(`PASS ${passed}: ${name}`)},ts=(date,h=8)=>new Date(`${date}T${String(h).padStart(2,"0")}:00:00+08:00`).toISOString(),event=(type,date,extra={},h=8)=>ledger.normalizeEvent({type,tradeDate:date,timestamp:ts(date,h),createdAt:ts(date,h),source:"TEST",...extra});
const cash=event("OPENING_CASH","2026-01-01",{grossAmount:100000}),position=event("OPENING_POSITION","2026-01-01",{symbol:"0050",quantity:100,unitPrice:50},9),base={version:ledger.VERSION,events:[cash,position],ledgerInitializedAt:ts("2026-01-01"),performanceStartDate:"2026-01-01",legacyMigrationVersion:ledger.MIGRATION_VERSION};
const add=(book,row)=>ledger.mutateLedger(book,{type:"ADD",event:row});
const generic=rows=>`trade_date,side,ticker,shares,unit_price,amount,fee,tax,memo\n${rows.join("\n")}`;

ok("01 normalize symbol preserves leading zero",()=>assert.equal(ledger.normalizeSymbol(" 0050 "),"0050"));
ok("02 split valid",()=>assert(event("SPLIT","2026-02-01",{symbol:"0050",ratio:2})));
ok("03 reverse split valid",()=>assert(event("REVERSE_SPLIT","2026-02-01",{symbol:"0050",ratio:.5})));
ok("04 stock dividend valid",()=>assert(event("STOCK_DIVIDEND","2026-02-01",{symbol:"0050",sharesPerShare:.1})));
ok("05 split zero invalid",()=>assert.equal(event("SPLIT","2026-02-01",{symbol:"0050",ratio:0}),null));
ok("06 split missing symbol invalid",()=>assert.equal(event("SPLIT","2026-02-01",{ratio:2}),null));
ok("07 stock dividend zero invalid",()=>assert.equal(event("STOCK_DIVIDEND","2026-02-01",{symbol:"0050",sharesPerShare:0}),null));
ok("08 split cash zero",()=>assert.equal(event("SPLIT","2026-02-01",{symbol:"0050",ratio:2}).cashImpact,0));
ok("09 split external zero",()=>assert.equal(event("SPLIT","2026-02-01",{symbol:"0050",ratio:2}).externalCashFlow,0));
ok("10 split quantity doubles",()=>{const r=add(base,event("SPLIT","2026-02-01",{symbol:"0050",ratio:2}));assert.equal(r.state.holdings[0].quantity,200)});
ok("11 split cost basis unchanged",()=>{const r=add(base,event("SPLIT","2026-02-01",{symbol:"0050",ratio:2}));assert.equal(r.state.holdings[0].costBasis,5000)});
ok("12 split average cost adjusts",()=>{const r=add(base,event("SPLIT","2026-02-01",{symbol:"0050",ratio:2}));assert.equal(r.state.holdings[0].averageCost,25)});
ok("13 reverse split quantity",()=>{const r=add(base,event("REVERSE_SPLIT","2026-02-01",{symbol:"0050",ratio:.5}));assert.equal(r.state.holdings[0].quantity,50)});
ok("14 stock dividend quantity",()=>{const r=add(base,event("STOCK_DIVIDEND","2026-02-01",{symbol:"0050",sharesPerShare:.1}));assert.equal(r.state.holdings[0].quantity,110)});
ok("15 action without holding blocked",()=>{const b={...base,events:[cash]},r=add(b,event("SPLIT","2026-02-01",{symbol:"0050",ratio:2}));assert.equal(r.status,"NO_HOLDING_FOR_ACTION")});
ok("16 sell after split valid",()=>{const r=add(base,event("SPLIT","2026-02-01",{symbol:"0050",ratio:2})),s=add(r.ledger,event("SELL","2026-03-01",{symbol:"0050",quantity:150,unitPrice:30}));assert(s.ok)});
ok("17 edit split full replay",()=>{const r=add(base,event("SPLIT","2026-02-01",{symbol:"0050",ratio:2})),id=r.ledger.events.find(x=>x.type==="SPLIT").id,e=ledger.mutateLedger(r.ledger,{type:"EDIT",id,event:event("SPLIT","2026-02-01",{symbol:"0050",ratio:3})});assert.equal(e.state.holdings[0].quantity,300)});
ok("18 delete split full replay",()=>{const r=add(base,event("SPLIT","2026-02-01",{symbol:"0050",ratio:2})),id=r.ledger.events.find(x=>x.type==="SPLIT").id,d=ledger.mutateLedger(r.ledger,{type:"DELETE",id});assert.equal(d.state.holdings[0].quantity,100)});
ok("19 delete needed action fail closed",()=>{let r=add(base,event("SPLIT","2026-02-01",{symbol:"0050",ratio:2}));r=add(r.ledger,event("SELL","2026-03-01",{symbol:"0050",quantity:150,unitPrice:30}));const id=r.ledger.events.find(x=>x.type==="SPLIT").id,d=ledger.mutateLedger(r.ledger,{type:"DELETE",id});assert.equal(d.status,"OVERSELL")});
ok("20 duplicate action detected",()=>{const e=event("SPLIT","2026-02-01",{symbol:"0050",ratio:2});assert(ledger.detectLikelyDuplicate([e],e))});

ok("21 healthy audit",()=>assert.equal(resilience.auditPortfolioData({ledger:base,knownSymbols:["0050"]}).status,"HEALTHY"));
ok("22 unsupported ledger",()=>assert.equal(resilience.auditPortfolioData({ledger:{version:"V0",events:[]}}).status,"UNSUPPORTED_VERSION"));
ok("23 duplicate id audit",()=>{const raw={...base,events:[cash,{...position,id:cash.id}]};assert.equal(resilience.auditPortfolioData({ledger:raw}).status,"REPAIR_REQUIRED")});
ok("24 invalid event audit",()=>{const raw={...base,events:[cash,{type:"BUY"}]};assert.equal(resilience.auditPortfolioData({ledger:raw}).status,"REPAIR_REQUIRED")});
ok("25 oversell audit",()=>{const raw={...base,events:[...base.events,event("SELL","2026-02-01",{symbol:"0050",quantity:200,unitPrice:50})]};assert.equal(resilience.auditPortfolioData({ledger:raw}).status,"REPAIR_REQUIRED")});
ok("26 invalid performance date",()=>assert.equal(resilience.auditPortfolioData({ledger:{...base,performanceStartDate:"bad"}}).status,"REPAIR_REQUIRED"));
ok("27 target warning",()=>assert.equal(resilience.auditPortfolioData({ledger:base,targets:{"0050":80}}).status,"WARNING"));
ok("28 invalid target",()=>assert.equal(resilience.auditPortfolioData({ledger:base,targets:{"0050":120}}).status,"REPAIR_REQUIRED"));
ok("29 unknown symbol warning",()=>assert.equal(resilience.auditPortfolioData({ledger:base,knownSymbols:["2330"]}).status,"WARNING"));
ok("30 orphan metadata warning",()=>assert.equal(resilience.auditPortfolioData({ledger:base,metadata:{"event:missing":{}}}).status,"WARNING"));
ok("31 snapshot mismatch warning",()=>{const s={date:"2026-01-02",cash:100000,holdings:{"0050":{quantity:99}}};assert.equal(resilience.auditPortfolioData({ledger:base,snapshots:[s]}).status,"WARNING")});
ok("32 audit read only",()=>{const before=JSON.stringify(base);resilience.auditPortfolioData({ledger:base});assert.equal(JSON.stringify(base),before)});
ok("33 repair preview only safe ops",()=>{const raw={...base,events:[position,cash]};assert.equal(resilience.previewRepair({ledger:raw}).status,"REPAIR_AVAILABLE")});
ok("34 repair applies deterministic sort",()=>{const raw={...base,events:[position,cash]},p=resilience.previewRepair({ledger:raw}),r=resilience.applyRepair({ledger:raw},p);assert(r.ok);assert.equal(r.data.ledger.events[0].type,"OPENING_CASH")});
ok("35 no unsafe auto repair",()=>{const raw={...base,events:[cash,{...position,id:cash.id}]};assert.equal(resilience.previewRepair({ledger:raw}).status,"NO_SAFE_REPAIR")});

const backup=resilience.createBackupV6({holdings:[{code:"0050"}],ledger:base,snapshots:[],rebalanceSettings:{targets:{"0050":100}},goal:{targetValue:1000000,targetDate:"2030-01-01"},monthlyPlan:{amount:10000},importState:{lastImportAt:ts("2026-01-02")},importHistory:[{importBatchId:"x"}],audit:{status:"HEALTHY"}});
ok("36 backup V6",()=>assert.equal(backup.version,6));
ok("37 backup schema",()=>assert.equal(backup.schema,"HS_PORTFOLIO_BACKUP_V6"));
ok("38 ledger preserved",()=>assert.equal(backup.ledger.events.length,2));
ok("39 target preserved",()=>assert.equal(backup.rebalanceSettings.targets["0050"],100));
ok("40 performance start preserved",()=>assert.equal(backup.performanceStartDate,"2026-01-01"));
ok("41 import provenance preserved",()=>assert.equal(backup.importHistory[0].importBatchId,"x"));
ok("42 preview V6",()=>assert(resilience.previewBackup(backup).ok));
ok("43 restore V6",()=>assert(resilience.restoreBackup(backup).ok));
ok("44 invalid V6 schema blocked",()=>assert(!resilience.previewBackup({...backup,schema:"BAD"}).ok));
ok("45 V5 migrates",()=>{const v5=workflow.createBackupV5({holdings:[],ledger:base});assert.equal(resilience.migrateBackup(v5).backup.version,6)});
ok("46 V4 migrates",()=>{const v4={...workflow.createBackupV5({holdings:[],ledger:base}),version:4};assert.equal(resilience.migrateBackup(v4).backup.version,6)});
ok("47 migration deterministic and idempotent",()=>{const v5=workflow.createBackupV5({holdings:[],ledger:base,exportedAt:"2026-01-01T00:00:00.000Z"});assert.equal(JSON.stringify(resilience.migrateBackup(v5)),JSON.stringify(resilience.migrateBackup(v5)));assert.equal(resilience.migrateBackup(backup).status,"ALREADY_CURRENT")});
ok("48 unsupported backup blocked",()=>assert.equal(resilience.previewBackup({version:3}).status,"UNSUPPORTED_VERSION"));
ok("49 recovery point",()=>assert.match(resilience.createRecoveryPoint({reason:"TEST",state:{ledger:base}}).id,/^recovery_/));
ok("50 recovery latest three",()=>{let p=[];for(let i=0;i<5;i++)p=resilience.appendRecoveryPoint(p,resilience.createRecoveryPoint({reason:`R${i}`,createdAt:`2026-01-0${i+1}T00:00:00Z`,state:{ledger:base}}));assert.equal(p.length,3);assert.equal(p[0].reason,"R2")});

const brokerText=generic(["2026-02-01,BUY,0050,10,60,,1,0,broker","2026-02-02,DEPOSIT,,,,1000,0,0,cash"]),adapter=resilience.detectBrokerAdapter(brokerText),brokerPreview=resilience.buildBrokerPreview(brokerText,base,{fileName:"fixture.csv"});
ok("51 generic adapter detected",()=>assert.equal(adapter.id,"GENERIC_BROKER_CSV_V1"));
ok("52 unknown adapter rejected",()=>assert.equal(resilience.detectBrokerAdapter("a,b\n1,2"),null));
ok("53 broker preview",()=>assert(brokerPreview.ok));
ok("54 broker symbol normalized",()=>assert.equal(brokerPreview.rows[0].event.symbol,"0050"));
ok("55 broker stable batch",()=>assert.equal(resilience.buildBrokerPreview(brokerText,base,{fileName:"fixture.csv"}).importBatchId,brokerPreview.importBatchId));
ok("56 broker malformed row",()=>{const p=resilience.buildBrokerPreview(generic(["bad,BUY,0050,10,60,,0,0,x"]),base);assert.equal(p.errors,1)});
ok("57 broker duplicate candidate",()=>{const e=event("BUY","2026-02-01",{symbol:"0050",quantity:10,unitPrice:60},12),b={...base,events:[...base.events,e]},p=resilience.buildBrokerPreview(brokerText,b);assert.equal(p.duplicates,1)});
ok("58 atomic broker import",()=>{const p=resilience.buildBrokerPreview(generic(["2026-02-01,DEPOSIT,,,,1000,0,0,cash"]),base),r=resilience.atomicBrokerImport(base,p,[0]);assert(r.ok)});
ok("59 provenance adapter",()=>{const p=resilience.buildBrokerPreview(generic(["2026-02-01,DEPOSIT,,,,1000,0,0,cash"]),base),r=resilience.atomicBrokerImport(base,p,[0]);assert.equal(r.ledger.events.at(-1).adapterId,"GENERIC_BROKER_CSV_V1")});
ok("60 provenance batch",()=>{const p=resilience.buildBrokerPreview(generic(["2026-02-01,DEPOSIT,,,,1000,0,0,cash"]),base),r=resilience.atomicBrokerImport(base,p,[0]);assert.equal(r.ledger.events.at(-1).importBatchId,p.importBatchId)});
ok("61 batch rollback",()=>{const p=resilience.buildBrokerPreview(generic(["2026-02-01,DEPOSIT,,,,1000,0,0,cash"]),base),r=resilience.atomicBrokerImport(base,p,[0]),back=resilience.rollbackImportBatch(r.ledger,p.importBatchId);assert(back.ok);assert.equal(back.ledger.events.length,2)});
ok("62 rollback preserves later manual",()=>{const p=resilience.buildBrokerPreview(generic(["2026-02-01,DEPOSIT,,,,1000,0,0,cash"]),base),r=resilience.atomicBrokerImport(base,p,[0]),manual=add(r.ledger,event("FEE","2026-02-02",{grossAmount:10})),back=resilience.rollbackImportBatch(manual.ledger,p.importBatchId);assert(back.ok);assert(back.ledger.events.some(x=>x.type==="FEE"))});
ok("63 missing batch blocked",()=>assert.equal(resilience.rollbackImportBatch(base,"missing").status,"BATCH_NOT_FOUND"));
ok("64 oversell batch import atomic",()=>{const p=resilience.buildBrokerPreview(generic(["2026-02-01,SELL,0050,999999,60,,0,0,bad"]),base),before=JSON.stringify(base),r=resilience.atomicBrokerImport(base,p,[0]);assert(!r.ok);assert.equal(JSON.stringify(base),before)});
ok("65 corporate actions excluded from TWR flows",()=>{const r=add(base,event("SPLIT","2026-02-01",{symbol:"0050",ratio:2})),t=ledger.calculateTwr({snapshots:[{date:"2026-01-01",totalAssets:105000},{date:"2026-02-01",totalAssets:105000}],events:r.ledger.events});assert.equal(t.value,0)});
ok("66 corporate actions excluded from XIRR flows",()=>{const r=add(base,event("SPLIT","2026-02-01",{symbol:"0050",ratio:2})),flows=ledger.buildXirrCashFlows(r.ledger,{date:"2026-12-31",value:110000});assert.equal(flows.length,2)});
ok("67 corporate actions excluded from recurring buys",()=>{const r=add(base,event("SPLIT","2026-02-01",{symbol:"0050",ratio:2})),a=workflow.recurringAnalytics(r.ledger,{asOf:"2026-02-20"});assert.equal(a.months.find(x=>x.month==="2026-02").buys,0)});
ok("68 calendar includes split",()=>{const r=add(base,event("SPLIT","2026-02-01",{symbol:"0050",ratio:2})),c=workflow.calendarMonth(r.ledger,"2026-02");assert.equal(c.days[0].events[0].type,"SPLIT")});
ok("69 original base immutable",()=>assert.equal(base.events.length,2));
ok("70 API frozen",()=>assert(Object.isFrozen(resilience)));
console.log(`Portfolio Resilience Phase 7: ${passed}/70 PASS`);
