const assert=require('assert');
const fs=require('fs');
const path=require('path');
const core=require('../final-core-production.js');
const canonical=require('../backtest/long-term/final-core-score-v1.js');
const strategy=require('../strategy-mode-core.js');
const html=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8');
let passed=0;
function test(name,fn){fn();passed++;console.log(`PASS ${passed}: ${name}`)}
function approx(a,b,e=1e-9){assert(Math.abs(a-b)<=e,`${a} != ${b}`)}
const fixture={ticker:'0050',j:-1.464767,k:30,d:30,dd52:-16.234230,crashRaw:-13.1804645,weeklyBias:-8,marketFear:70,valuation:55};
const result=core.buildFinal(fixture);
test('canonical version',()=>assert.equal(core.LONG_TERM_CORE_SCORE_VERSION,'FINAL_CORE_WEIGHT_V1'));
test('canonical weights',()=>assert.deepEqual(canonical.WEIGHTS,{weeklyJ:30,dd52:55,crash:15}));
test('weekly J frozen mapping',()=>assert.equal(result.coreFactors.weeklyJ.score,95));
test('DD52 frozen mapping',()=>assert.equal(result.coreFactors.dd52.score,54));
test('crash frozen mapping',()=>approx(result.coreFactors.crash.score,32.721858,1e-6));
test('J contribution',()=>approx(result.coreFactors.weeklyJ.contribution,28.5));
test('DD52 contribution',()=>approx(result.coreFactors.dd52.contribution,29.7));
test('crash contribution',()=>approx(result.coreFactors.crash.contribution,4.9082787,1e-6));
test('exact score',()=>approx(result.coreScore,63.1082787,1e-6));
test('display floor',()=>assert.equal(result.coreScoreDisplay,63));
test('label',()=>assert.equal(result.label,'正式加碼訊號'));
test('trigger',()=>assert.equal(result.historicalTriggerRate,9));
test('fail closed missing J',()=>assert.equal(core.buildFinal({...fixture,j:null}).coreScore,null));
test('fail closed missing DD52',()=>assert.equal(core.buildFinal({...fixture,dd52:null}).coreScore,null));
test('fail closed missing crash',()=>assert.equal(core.buildFinal({...fixture,crashRaw:null,rows:[]}).coreScore,null));
test('no renormalization',()=>assert.equal(core.buildFinal({...fixture,crashRaw:null,rows:[]}).coreScoreDisplay,null));
test('009815 unavailable',()=>assert.equal(core.buildFinal({...fixture,ticker:'009815'}).score,null));
test('auxiliary excluded',()=>assert.equal(core.buildFinal({...fixture,valuation:0,marketFear:0,weeklyBias:99}).coreScore,result.coreScore));
test('all labels exact',()=>assert.deepEqual([0,30,40,45,50,65,70,80,90].map(x=>core.labelFor(x).label),['一般持有','回檔訊號出現','加碼條件浮現','試探加碼','正式加碼訊號','積極加碼訊號','強力加碼訊號','重大加碼機會','歷史極端機會']));
test('threshold exact not display',()=>assert.equal(canonical.meetsFinalCoreThresholdV1(49.999,50),false));
test('ranking exact score',()=>assert(core.compare({ticker:'B',coreScore:50.9},{ticker:'A',coreScore:50.1})<0));
test('ranking deterministic tie',()=>assert(core.compare({ticker:'A',coreScore:50},{ticker:'B',coreScore:50})<0));
test('legacy rollback',()=>assert.equal(core.buildDecision(fixture,{score:77},core.LEGACY_VERSION).score,77));
test('default final',()=>assert.equal(core.buildDecision(fixture,{score:77},'INVALID').coreScoreVersion,'FINAL_CORE_WEIGHT_V1'));
test('schema complete',()=>['coreScore','coreScoreDisplay','coreScoreVersion','coreFactors','label','historicalTriggerRate','auxiliary'].forEach(k=>assert(k in result)));
test('UI version 2.0',()=>assert(/HS ETF 股市雷達 2\.0/.test(html)&&!/VERSION 6\.2/.test(html)));
test('UI canonical scripts',()=>assert(html.includes('final-core-score-v1.js')&&html.includes('final-core-production.js')));
test('UI score sheet',()=>assert(html.includes('讀懂你的分數')&&html.includes('coreScoreLadder')));
test('P2/P3 stores preserved',()=>assert(html.includes('schema_version:3')&&html.includes('dailyLongRank.v1')));
test('P1/P4 marketAsOf preserved',()=>assert(html.includes('latestSuccessfulMarketAsOf')&&html.includes('intraday.asOf')));
console.log(`Phase 6B production guards: ${passed}/30 PASS`);
