const assert=require("assert"),fs=require("fs"),path=require("path"),vm=require("vm");
const root=path.resolve(__dirname,".."),html=fs.readFileSync(path.join(root,"index.html"),"utf8"),css=fs.readFileSync(path.join(root,"formal-black-gold.css"),"utf8"),contract=require(path.join(root,"hs-decision-layer-v1.js"));
const start=html.indexOf("function radarOverviewNextLevel"),end=html.indexOf("function radarRangeBar",start);assert(start>=0&&end>start);
const context={Number,Math,String,Array,Map,Object,window:{HSDecisionLayerV1:contract},researchC4HistoryArtifacts:new Map(),researchC4HistoryStatus:new Map(),esc:value=>String(value)};
vm.createContext(context);vm.runInContext(`${html.slice(start,end)};this.api={card:radarTodayFocusCard,html:radarTodayFocusHtml};`,context);
const rows=(scores)=>scores.map((displayScore,index)=>({symbol:"00830",displayScore,tradingDate:`2026-09-${String(18-index).padStart(2,"0")}`}));
const card=(current,previous,options={})=>context.api.card({symbol:options.symbol||"00830",name:options.name||"國泰費城半導體",rows:rows([current,previous,...(options.older||[])]),percentile:options.percentile??null},contract);
const event=(value,type)=>value?.events.find(item=>item.type===type);

assert.match(event(card(31,29),"CROSS_LEVEL").text,/進入「回檔訊號出現」/);
assert.match(event(card(40,39),"CROSS_LEVEL").text,/進入「加碼條件浮現」/);
assert.match(event(card(45,44),"CROSS_LEVEL").text,/進入「試探加碼」/);
assert.match(event(card(50,49),"CROSS_LEVEL").text,/進入「正式加碼訊號」/);
assert.match(event(card(43,46),"CROSS_LEVEL").text,/由「試探加碼」回到「加碼條件浮現」/);
assert.equal(event(card(39,39),"NEXT_LEVEL").text,"距「加碼條件浮現」還差 1 分");
assert.equal(event(card(38,38),"NEXT_LEVEL").text,"距「加碼條件浮現」還差 2 分");
assert.equal(card(37,37),null);
assert.equal(event(card(20,20,{percentile:85}),"HISTORICAL_PERCENTILE").text,"P85");
assert.equal(card(20,20,{percentile:84}),null);
assert.match(event(card(25,25,{older:[25,25,25,15]}),"FIVE_DAY_CHANGE").text,/上升 10 分/);
assert.equal(card(24,24,{older:[24,24,24,15]}),null);
const merged=card(39,29,{percentile:90,older:[30,25,20,15]});assert(merged);assert.equal(merged.events.length,3);assert.deepEqual(Array.from(merged.events,item=>item.type),["CROSS_LEVEL","NEXT_LEVEL","HISTORICAL_PERCENTILE"]);
assert.equal(card(22,22,{percentile:50,older:[22,22,22,22]}),null);
const waitNative=card(39,39,{symbol:"009815"});assert(waitNative);assert.equal(waitNative.events.some(item=>item.type==="HISTORICAL_PERCENTILE"),false);
const multi=card(51,39);assert.equal(event(multi,"CROSS_LEVEL").note,"本次跨越多個分級");
const rendered=context.api.html({cards:[merged,waitNative,{...merged,symbol:"0050"}],latestDate:"2026-09-18"});assert.equal((rendered.match(/class="radarTodayFocusCard"/g)||[]).length,3);assert.match(rendered,/查看詳情/);assert.match(html,/function radarTodayFocusState[\s\S]*?\.slice\(0,3\)/);
assert.match(context.api.html({cards:[],latestDate:"2026-09-18"}),/目前沒有新的重要狀態變化[。\s\S]*2026-09-18/);
assert.match(html,/data-radar-focus-phase="9"/);assert.match(html,/20260919-radar-notifications-phase11b1/);assert.match(html,/依最新正式盤後資料/);
for(const forbidden of ["最佳 ETF","Top Pick","最值得買","買進建議","預測報酬","勝率排序"])assert(!html.includes(forbidden));
assert.match(css,/\.radarTodayFocusCards\{[^}]*grid-template-columns:repeat\(3,minmax\(0,1fr\)\)/);assert.match(css,/@media\(max-width:700px\)\{\.radarTodayFocusCards\{grid-template-columns:1fr\}/);assert.match(css,/\.radarTodayFocusCard footer\{[^}]*font-size:10px/);
const artifact=JSON.parse(fs.readFileSync(path.join(root,"finalized-core-score-snapshots-v1.json"),"utf8")),names={"0050":"元大台灣50","00662":"富邦NASDAQ","00757":"統一FANG+","00830":"國泰費城半導體","00935":"野村臺灣新科技50","009815":"大華美國MAG7+"};
const actual=Object.keys(names).map(symbol=>{const history=artifact.snapshots.filter(snapshot=>snapshot.snapshot_type==="FINALIZED_CLOSE"&&snapshot.finalized===true).sort((a,b)=>String(b.date).localeCompare(String(a.date))).map(snapshot=>{const item=(snapshot.rows||[]).find(row=>row.symbol===symbol);return item&&Number.isFinite(item.final_core_score)?{symbol,displayScore:Math.floor(item.final_core_score),tradingDate:snapshot.date}:null}).filter(Boolean).slice(0,6);let percentile=null,researchPath=path.join(root,"research","c4_historical",`${symbol}.json`);if(fs.existsSync(researchPath)&&history[0]){const research=JSON.parse(fs.readFileSync(researchPath,"utf8")),values=(research.records||[]).map(row=>Number(row.display_score)).filter(Number.isFinite);if(values.length)percentile=Math.round(values.filter(value=>value<=history[0].displayScore).length/values.length*100)}return context.api.card({symbol,name:names[symbol],rows:history,percentile},contract)}).filter(Boolean).sort((a,b)=>a.priority-b.priority||a.symbol.localeCompare(b.symbol)).slice(0,3);
console.log("PRODUCTION FOCUS",JSON.stringify(actual.map(item=>({symbol:item.symbol,score:item.score,events:item.events.map(event=>event.type)}))));
console.log("PASS ETF Radar Phase 9 finalized-only Decision Focus rules, dedupe, empty state and mobile layout");
