const assert=require("node:assert/strict");
const fs=require("node:fs");
const path=require("node:path");
const ledger=require("../portfolio-ledger-core.js");
const performance=require("../portfolio-performance-core.js");
const backup=require("../portfolio-full-backup-core.js");
const dashboard=require("../portfolio-dashboard-core.js");
const root=path.resolve(__dirname,"..");
const html=fs.readFileSync(path.join(root,"index.html"),"utf8");
const ui=fs.readFileSync(path.join(root,"portfolio-v6.js"),"utf8");
const css=fs.readFileSync(path.join(root,"portfolio-v6.css"),"utf8");
const date="2026-09-24",time="2026-09-24T09:30:00+08:00";
const event=(type,extra={})=>ledger.normalizeEvent({type,tradeDate:date,timestamp:time,source:"TEST",...extra});
const empty=ledger.migrateLegacyPortfolio({holdings:[],cash:0,tradeDate:date,timestamp:time});
const add=(source,type,extra={})=>ledger.mutateLedger(source,{type:"ADD",event:event(type,extra)});
const cases=[];const check=(name,fn)=>{fn();cases.push(name);console.log(`PASS ${cases.length} ${name}`)};

check("zero cash buy accepted",()=>assert(add(empty,"BUY",{symbol:"0050",quantity:2,unitPrice:10}).ok));
check("buy yields signed negative cash",()=>assert.equal(add(empty,"BUY",{symbol:"0050",quantity:2,unitPrice:10}).state.cash,-20));
check("negative cash survives ledger validate and reload",()=>{const result=add(empty,"BUY",{symbol:"0050",quantity:2,unitPrice:10});assert.equal(ledger.derivePortfolioStateFromLedger(ledger.validateLedger(JSON.parse(JSON.stringify(result.ledger))).events).cash,-20)});
check("oversell remains blocked",()=>{const result=add(empty,"BUY",{symbol:"0050",quantity:2,unitPrice:10});assert.equal(add(result.ledger,"SELL",{symbol:"0050",quantity:3,unitPrice:10}).status,"OVERSELL")});
check("deposit increases canonical cash",()=>assert.equal(add(empty,"DEPOSIT",{grossAmount:100}).state.cash,100));
check("withdrawal decreases canonical cash",()=>assert.equal(add(empty,"WITHDRAWAL",{grossAmount:100}).state.cash,-100));
check("deposit record survives ledger reload",()=>{const result=add(empty,"DEPOSIT",{grossAmount:100});assert.equal(ledger.validateLedger(JSON.parse(JSON.stringify(result.ledger))).events.at(-1).type,"DEPOSIT")});
check("hero has total assets and signed cash",()=>{assert.match(html,/id="portfolioHeroTotalAssets"/);assert.match(html,/id="portfolioHeroCash"/);assert.match(ui,/money\(\(summary\.stockMarketValue\|\|0\)\+cash\)/)});
check("targets use existing holdings and settings storage",()=>{assert.match(ui,/saveTargetBatch[\s\S]*saveHoldings\(\);saveRebalanceSettings\(\)/);assert.doesNotMatch(ui,/TARGET_STORAGE_KEY/)});
check("target removal keeps holding and Ledger",()=>{assert.match(ui,/holdings\.map\(item=>\{const targetAllocation=targetDraft\.has/);assert.match(ui,/targetDraft\.delete/);assert.doesNotMatch(ui.slice(ui.indexOf("function saveTargetBatch"),ui.indexOf("function rebalanceTrend")),/deleteHolding|mutateLedger/)});
check("unheld ETF can enter target list",()=>assert.deepEqual(dashboard.targetAllocationItems([], {"00662":20}).map(row=>row.code),["00662"]));
check("incomplete target can be edited",()=>{assert.equal(dashboard.targetSummary([70]).status,"under");assert.match(ui,/targetDraft\.set\(code,""\)/)});
check("incomplete target cannot save",()=>assert.match(ui,/if\(!summary\.complete\)/));
check("100 percent target saves",()=>assert.equal(dashboard.targetSummary([20,30,50]).complete,true));
const rows=[{code:"0050",targetAllocation:20,marketValue:500,price:10},{code:"00662",targetAllocation:30,marketValue:100,price:10},{code:"00830",targetAllocation:50,marketValue:0,price:10}];
const plan=performance.buildCashOnlyRebalancePlan({rows,availableCash:400});
check("target value uses existing holdings plus cash",()=>assert.equal(plan.rows.find(row=>row.symbol==="0050").gap,0));
check("overweight ETF gets zero",()=>assert.equal(plan.rows.find(row=>row.symbol==="0050").allocationAmount,0));
check("underweight ETFs receive cash",()=>assert(plan.rows.find(row=>row.symbol==="00662").allocationAmount>0&&plan.rows.find(row=>row.symbol==="00830").allocationAmount>0));
check("insufficient cash scales by positive gaps",()=>{const a=plan.rows.find(row=>row.symbol==="00662"),b=plan.rows.find(row=>row.symbol==="00830");assert.equal(a.gap,200);assert.equal(b.gap,500);assert(Math.abs(a.budget/b.budget-200/500)<.01)});
check("missing quote fails closed",()=>assert.equal(performance.buildCashOnlyRebalancePlan({rows:[{...rows[0],price:null},{...rows[1],targetAllocation:80}],availableCash:100}).status,"PRICE_UNAVAILABLE"));
check("nonpositive cash creates no buy",()=>{for(const cash of [0,-100]){const result=performance.buildCashOnlyRebalancePlan({rows,availableCash:cash});assert.equal(result.status,"NO_CASH");assert(result.rows.every(row=>row.allocationAmount===0))}});
check("nonpositive cash is explained even when quotes are unavailable",()=>assert.match(ui,/cash<=0\?"目前沒有可配置現金。"/));
check("target input has iOS-safe CSS",()=>assert.match(css,/\.portfolioTargetBatchRow input[^\n]*font-size:16px!important/));
check("negative cash snapshot is valid",()=>{const row={date,timestamp:time,totalMarketValue:20,cash:-30,totalAssets:-10,unrealizedPnL:0,holdings:{"0050":{quantity:2,marketPrice:10,marketValue:20}}};assert.equal(performance.validateSnapshot(row).cash,-30)});
check("negative cash full backup round trip",()=>{class Storage{constructor(){this.map=new Map()}get length(){return this.map.size}key(i){return [...this.map.keys()][i]??null}getItem(k){return this.map.get(k)??null}setItem(k,v){this.map.set(k,String(v))}removeItem(k){this.map.delete(k)}}const store=new Storage(),settings={cash:-20,profile:"trend",customTolerance:3,reminder:"90",customDays:60,cashFirst:true,trendProtection:true,targets:{}};store.setItem("hsRadar.portfolio.holdings",JSON.stringify([]));store.setItem("hsRadar.portfolio.rebalanceSettings",JSON.stringify(settings));const captured=backup.createBackup(store);assert.equal(captured.portfolio.cash,-20);store.setItem("hsRadar.portfolio.rebalanceSettings",JSON.stringify({...settings,cash:0}));assert(backup.restoreAtomic(store,captured).ok);assert.equal(backup.createBackup(store).portfolio.cash,-20)});
check("cash sheet uses the same Ledger",()=>{assert.match(html,/id="portfolioCashModal"/);assert.match(ui,/function submitCash[\s\S]*ledgerCore\.mutateLedger\(ledger,\{type:"ADD",event:entry\}\)/)});
check("advanced tools collapsed by default",()=>{assert.match(html,/id="portfolioMoreTools"/);assert.match(css,/portfolioPage:not\(\.portfolioMoreOpen\)>\[data-portfolio-tool\]/)});
console.log(`${cases.length}/${cases.length} Portfolio UX cash/rebalance tests PASS`);
