"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm"),production=require("../final-core-production.js");
const html=fs.readFileSync(path.join(__dirname,"..","index.html"),"utf8"),start=html.indexOf("function isCompletedTradingDate"),end=html.indexOf("function longOverviewCardHtml");
const localSnapshots=Array.from({length:370},(_,i)=>({snapshot_type:"FINALIZED_CLOSE",tradingDate:`2026-01-${String((i%28)+1).padStart(2,"0")}`,items:{}}));
const context={Date,Number,Array,Object,Math,Set,HSFinalCoreProduction:production,LONG_TERM_CORE_SCORE_VERSION:"FINAL_CORE_WEIGHT_V1",loadDailyLongRankHistory:()=>({schema_version:1,snapshots:[]}),finalizedCoreScoreHistoryArtifact:{schema_version:1,core_score_version:"FINAL_CORE_WEIGHT_V1",snapshots:[]},coreScoreTrendRanges:new Map(),esc:value=>String(value)};vm.createContext(context);vm.runInContext(html.slice(start,end),context);
const row=(symbol,date,score)=>({symbol,final_core_score:score,tier:production.labelFor(score).label,core_score_version:"FINAL_CORE_WEIGHT_V1",data_as_of:`${date}T13:30:00+08:00`,factors:{weekly_j:{raw:1,score:60,weight:30,contribution:18},dd52:{raw:-10,score:50,weight:55,contribution:27.5},crash:{raw:-5,score:30,weight:15,contribution:4.5}}});
const tradingDates=count=>{const dates=[],cursor=new Date(Date.UTC(2026,0,1));while(dates.length<count){if(cursor.getUTCDay()>0&&cursor.getUTCDay()<6)dates.push(cursor.toISOString().slice(0,10));cursor.setUTCDate(cursor.getUTCDate()+1)}return dates};
const artifact=count=>({schema_version:1,core_score_version:"FINAL_CORE_WEIGHT_V1",snapshots:tradingDates(count).map(date=>({date,snapshot_type:"FINALIZED_CLOSE",finalized:true,finalized_at:`${date}T13:30:00+08:00`,rows:[row("0050",date,50)]}))});
context.finalizedCoreScoreHistoryArtifact=artifact(5);let state=context.coreScoreHistoryState("0050");assert.equal(state.officialCount,5);assert.equal(state.range,"10D");assert.equal(state.rows.length,5);console.log("PASS official source and partial accumulation");
context.finalizedCoreScoreHistoryArtifact=artifact(20);context.coreScoreTrendRanges.set("0050","1M");state=context.coreScoreHistoryState("0050");assert.equal(state.range,"1M");assert.equal(state.rows.length,20);console.log("PASS 1M unlock only at 20 official rows");
context.finalizedCoreScoreHistoryArtifact=artifact(59);context.coreScoreTrendRanges.set("0050","3M");state=context.coreScoreHistoryState("0050");assert.equal(state.range,"10D");assert.equal(state.officialCount,59);context.finalizedCoreScoreHistoryArtifact=artifact(60);state=context.coreScoreHistoryState("0050");assert.equal(state.range,"3M");assert.equal(state.rows.length,60);console.log("PASS 3M unlock only at 60 official rows");
context.finalizedCoreScoreHistoryArtifact=artifact(5);const local={schema_version:1,snapshots:tradingDates(30).map(date=>({snapshot_type:"FINALIZED_CLOSE",tradingDate:date,items:{"0050":{final_core_score:30,display_score:30,data_as_of:`${date}T13:30:00+08:00`,engine_version:"FINAL_CORE_WEIGHT_V1",weekly_j:1}}}))};state=context.coreScoreHistoryState("0050",local);assert.equal(state.source,"local");assert.equal(state.officialCount,5);assert.equal(state.rows.length,10);assert.equal(context.coreScoreHistoryState("009815",local).kind,"wait_native");console.log("PASS fallback remains isolated; local history cannot unlock ranges or affect 009815");
const conflictDate="2026-08-26",previousDate="2026-08-25",symbols=["00830","0050","00662","00757","00935"];
context.coreScoreTrendRanges.clear();
context.finalizedCoreScoreHistoryArtifact={schema_version:1,core_score_version:"FINAL_CORE_WEIGHT_V1",snapshots:[{date:conflictDate,snapshot_type:"FINALIZED_CLOSE",finalized:true,finalized_at:`${conflictDate}T13:30:00+08:00`,rows:symbols.map((symbol,index)=>row(symbol,conflictDate,symbol==="00830"?53.8031197301855:40+index))}]};
const conflictLocal={schema_version:1,snapshots:[
  {snapshot_type:"FINALIZED_CLOSE",tradingDate:previousDate,items:Object.fromEntries(symbols.map(symbol=>[symbol,{final_core_score:47,display_score:47,data_as_of:`${previousDate}T13:30:00+08:00`,engine_version:"FINAL_CORE_WEIGHT_V1",weekly_j:1}]))},
  {snapshot_type:"FINALIZED_CLOSE",tradingDate:conflictDate,items:Object.fromEntries(symbols.map(symbol=>[symbol,{final_core_score:symbol==="00830"?47:99,display_score:symbol==="00830"?47:99,data_as_of:`${conflictDate}T13:30:00+08:00`,engine_version:"FINAL_CORE_WEIGHT_V1",weekly_j:1}]))}
]};
state=context.coreScoreHistoryState("00830",conflictLocal);assert.equal(state.rows[0].tradingDate,conflictDate);assert.equal(state.rows[0].displayScore,53);assert.equal(state.rows[0].historySource,"official");assert.equal(state.source,"official");assert.equal(state.seriesSource,"mixed");assert.equal(state.rows.filter(entry=>entry.tradingDate===conflictDate).length,1);assert.equal(state.rows.find(entry=>entry.tradingDate===previousDate).displayScore,47);console.log("PASS same-date finalized 00830 score overrides local fallback without duplicates");
for(const symbol of symbols.filter(symbol=>symbol!=="00830")){const other=context.coreScoreHistoryState(symbol,conflictLocal);assert.equal(other.rows[0].displayScore,40+symbols.indexOf(symbol));assert.equal(other.rows[0].historySource,"official");}
console.log("PASS same-date official precedence is generic across existing ETFs");
assert.match(html,/historyLabel=state\.source==="official"\?"正式盤後":"本機盤後試算"/);assert.match(html,/最新\$\{historyLabel\} \$\{latestScore\}/);console.log("PASS latest source wording follows the selected finalized observation");
assert.match(html,/loadFinalizedCoreScoreHistory/);assert.match(html,/finalized-core-score-snapshots-v1\.json/);assert.match(html,/data-core-trend-range/);console.log("PASS production artifact loader and range UI contract");
assert.match(html,/function officialDailyLongRankPair/);assert.match(html,/source:"official"/);assert.match(html,/本機盤後試算/);console.log("PASS official daily pair precedence and source-visible local fallback");
