"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm");
const root=path.resolve(__dirname,".."),html=fs.readFileSync(path.join(root,"index.html"),"utf8");
const core=require(path.join(root,"final-core-production.js")),validation=require(path.join(root,"c4-validation-metadata.js"));
const source=(name,next)=>{const start=html.indexOf(`function ${name}(`);assert(start>=0,name);const end=html.indexOf(`function ${next}(`,start);assert(end>start,next);return html.slice(start,end).replace(/\basync\s*$/,"")};
assert.deepEqual(Object.values(validation.STATUS),["FORMAL","VALIDATING","REFERENCE"]);
for(const symbol of core.SUPPORTED_TICKERS)assert.equal(validation.resolve(symbol).status,"FORMAL",symbol);
for(const symbol of ["00635U","2330","009815","00631L","09999Z","12345A"])assert.equal(validation.resolve(symbol).status,"REFERENCE",symbol);
assert.equal(Object.keys(validation.VALIDATING_METADATA).length,0,"no active C4-specific validation record has been established");
const validating=validation.createResolver({core,validatingMetadata:{"00878":{status:"VALIDATING",method:"BENCHMARK_VALIDATION",since:"2026-09-25"},"0050":{status:"VALIDATING",method:"FORWARD_SHADOW"},"00635U":{status:"VALIDATING"}}});
assert.equal(validating.resolve("00878").status,"VALIDATING");
assert.equal(validating.resolve("0050").status,"FORMAL","formal eligibility always wins");
assert.equal(validating.resolve("00635U").status,"REFERENCE","an unsubstantiated validating label must not be promoted");
assert.equal(validation.createResolver({core:{SUPPORTED_TICKERS:["NEWETF"]}}).resolve("NEWETF").status,"FORMAL","formal follows the existing core source");
assert.equal(validation.createResolver({core:{SUPPORTED_TICKERS:[]}}).resolve("0050").status,"REFERENCE","no duplicated formal list may survive an eligibility change");
const moduleSource=fs.readFileSync(path.join(root,"c4-validation-metadata.js"),"utf8");
assert.match(moduleSource,/core\?\.SUPPORTED_TICKERS\?\.includes\(ticker\)/);
assert.doesNotMatch(moduleSource,/buildFinal|buildAdHocScore|final_core_score|LONG_RADAR_SCORED_CODES/);
assert.match(html,/<script src="final-core-production\.js[^\"]*"><\/script>\s*<script src="c4-validation-metadata\.js[^\"]*"><\/script>/);
const blocks=[source("renderWatchAdHocResult","queryWatchAdHoc"),source("watchDiagnosticCard","renderWatchDiagnostics"),source("openWatchDiagnostic","closeWatchDiagnostic")];
for(const block of blocks)assert.match(block,/window\.HSC4ValidationMetadata\.resolve\(/,"each view must use the single resolver");
assert.doesNotMatch(html,/function watchValidationStatus\(|function watchValidationInfo\(/);
const nodes=new Map(),node=id=>{if(!nodes.has(id))nodes.set(id,{innerHTML:"",textContent:"",classList:{add(){}},setAttribute(){},focus(){},querySelector(){return null}});return nodes.get(id)};
const watchlist=[{id:"00635U",name:"黃金ETF"},{id:"2330",name:"台積電"}];
const context={window:{HSC4ValidationMetadata:validation},HSFinalCoreProduction:core,currentFormalCoreScoreForSymbol:()=>({available:true,score:39.4,display_score:39,trading_date:"2026-09-24"}),watchlist,watchDiagnosticState:new Map(),$:node,esc:value=>String(value??""),fmt:value=>String(value),signed:value=>String(value),watchDirectionIcon:()=>"→",watchMetric:()=>"—",watchDiagnosticSection:(title)=>`<section>${title}</section>`,adHocReasonText:()=>"歷史行情不足，尚無法完整計算 C4。",lastWatchDiagnosticTrigger:null};
vm.createContext(context);
vm.runInContext(source("watchUnavailableState","adHocComponentRow")+"\n"+source("adHocComponentRow","renderWatchAdHocResult")+"\n"+blocks.join("\n"),context);
const score=(ticker)=>({available:true,ticker,name:ticker,score:23.4,displayScore:23,tier:"一般持有",scoreAsOf:"2026-09-24",components:{}});
const diagnostic={price:100,changeValue:null,changePct:null,trend:null,pullback:null,weekly:null,rs:null,recovery:null,dataAsOf:"2026-09-24"};
for(const symbol of ["00635U","2330"]){
  const resolved=validation.resolve(symbol);
  context.renderWatchAdHocResult({kind:"ready",ticker:symbol,score:score(symbol)});
  const quick=node("#watchAdHocResult").innerHTML;
  const watch=context.watchDiagnosticCard({id:symbol,name:symbol},{kind:"ready",diagnostic,adHoc:score(symbol)});
  context.watchDiagnosticState.set(symbol,{kind:"ready",diagnostic,adHoc:score(symbol)});
  context.openWatchDiagnostic(symbol,null);
  const detail=node("#watchDiagnosticContent").innerHTML;
  for(const rendered of [quick,watch,detail])assert.match(rendered,new RegExp(resolved.label));
  assert.match(quick,/HS C4[\s\S]*>23</);assert.match(watch,/HS C4[\s\S]*>23</);assert.match(detail,/HS C4 23/);
}
context.renderWatchAdHocResult({kind:"ready",ticker:"00635U",score:{available:false,reason:"INSUFFICIENT_DAILY_HISTORY"}});
assert.match(node("#watchAdHocResult").innerHTML,/HS C4 暫無分數/);
assert.doesNotMatch(node("#watchAdHocResult").innerHTML,/HS C4 0|驗證中/);
assert.equal(context.watchScoreForDisplay("00830",score("00830")).score,39.4,"validation status cannot replace canonical formal score");
assert.equal(context.watchScoreForDisplay("00635U",score("00635U")).score,23.4,"reference status cannot change the research score");
assert.equal(validating.resolve("00878").status,"VALIDATING");
assert.equal(context.watchScoreForDisplay("00635U",score("00635U")).tier,"一般持有","validation cannot alter tier");
console.log("PASS C4 validation metadata: single source, formal eligibility, validating fixture, reference fallback, cross-view parity, unavailable guard and score isolation");
