"use strict";
const assert=require("node:assert/strict");
const fs=require("node:fs");
const path=require("node:path");
const root=path.resolve(__dirname,"..");
const html=fs.readFileSync(path.join(root,"index.html"),"utf8");
const css=fs.readFileSync(path.join(root,"formal-black-gold.css"),"utf8");

assert.match(html,/function radarScoreTrendHtml\(x\)/);
assert.match(html,/近期趨勢與訊號/);
assert.match(html,/data-radar-trend-phase="4"/);
assert.match(html,/"10D":10,"20D":20,"60D":60,"120D":120/);
assert.match(html,/officialArtifactCoreScoreHistory\(artifact,x\?\.id,120\)/);
assert.match(html,/snapshot\?\.snapshot_type!=="FINALIZED_CLOSE"/);
assert.match(html,/snapshot\?\.finalized!==true/);
assert.match(html,/正式盤後資料暫缺；不以盤中或本機資料補值/);
assert.match(html,/等待原生資料；不產生趨勢、價格表現或訊號/);
assert.match(css,/\.radarTrendP4Prices\{display:grid;grid-template-columns:repeat\(4,minmax\(0,1fr\)\)/);
assert.match(css,/@media\(max-width:600px\)[\s\S]*\.radarTrendP4Prices\{grid-template-columns:repeat\(2,minmax\(0,1fr\)\)/);
assert.match(css,/\.radarTrendPhase4 \.radarTrendP4Chart svg\{display:block;width:100%/);
console.log("PASS ETF Radar Phase 4 finalized-only trend presentation guard");
