const assert=require("assert"),core=require("../portfolio-ledger-core.js");let passed=0;
const fs=require("fs"),path=require("path"),root=path.join(__dirname,".."),html=fs.readFileSync(path.join(root,"index.html"),"utf8"),ui=fs.readFileSync(path.join(root,"portfolio-v6.js"),"utf8"),css=fs.readFileSync(path.join(root,"portfolio-v6.css"),"utf8");
const ok=(name,fn)=>{fn();passed++;console.log(`PASS ${passed}: ${name}`)},ts=(date,n=0)=>`${date}T${String(1+n).padStart(2,"0")}:00:00+08:00`;
const ev=(type,date,extra={},n=0)=>core.normalizeEvent({type,tradeDate:date,timestamp:ts(date,n),createdAt:ts(date,n),source:"TEST",...extra});
const ledger=(events,start="2026-01-01")=>({version:core.VERSION,events,ledgerInitializedAt:ts(start),performanceStartDate:start,legacyMigrationVersion:core.MIGRATION_VERSION});
const opening=[ev("OPENING_CASH","2026-01-01",{grossAmount:100000}),ev("OPENING_POSITION","2026-01-01",{symbol:"0050",quantity:100,unitPrice:50},1)];
ok("1 empty portfolio migration",()=>assert.equal(core.migrateLegacyPortfolio({holdings:[],cash:0,tradeDate:"2026-01-01",timestamp:ts("2026-01-01")}).events.length,0));
const migration=core.migrateLegacyPortfolio({holdings:[{code:"0050",shares:100,averageCost:50},{code:"00830",shares:20,averageCost:80}],cash:1234,tradeDate:"2026-01-01",timestamp:ts("2026-01-01")});
ok("2 legacy holdings become opening positions",()=>assert.equal(migration.events.filter(x=>x.type==="OPENING_POSITION").length,2));
ok("3 legacy cash becomes opening cash",()=>assert.equal(migration.events.find(x=>x.type==="OPENING_CASH").grossAmount,1234));
ok("4 migration version is stable",()=>assert.equal(migration.legacyMigrationVersion,core.MIGRATION_VERSION));
ok("5 validated migration does not duplicate on refresh",()=>assert.equal(core.validateLedger(migration).events.length,3));
ok("6 average cost preserved",()=>assert.equal(core.derivePortfolioStateFromLedger(migration.events).holdings[0].averageCost,50));
ok("7 migration creates no fake buy",()=>assert(!migration.events.some(x=>x.type==="BUY")));
ok("8 performance start date",()=>assert.equal(migration.performanceStartDate,"2026-01-01"));
ok("9 opening position",()=>assert.equal(core.derivePortfolioStateFromLedger([opening[1]]).holdings[0].quantity,100));
ok("10 opening cash",()=>assert.equal(core.derivePortfolioStateFromLedger([opening[0]]).cash,100000));
const buy=ev("BUY","2026-01-02",{symbol:"0050",quantity:100,unitPrice:60,fee:10});
ok("11 buy",()=>assert.equal(core.derivePortfolioStateFromLedger([...opening,buy]).cash,93990));
ok("12 multiple buys weighted average",()=>assert.equal(core.derivePortfolioStateFromLedger([...opening,buy]).holdings[0].averageCost,55.05));
const sell=ev("SELL","2026-01-03",{symbol:"0050",quantity:50,unitPrice:70,fee:10,tax:5});
ok("13 partial sell",()=>assert.equal(core.derivePortfolioStateFromLedger([...opening,buy,sell]).holdings[0].quantity,150));
const full=ev("SELL","2026-01-04",{symbol:"0050",quantity:150,unitPrice:70});
ok("14 full sell",()=>assert.equal(core.derivePortfolioStateFromLedger([...opening,buy,sell,full]).holdings.length,0));
ok("15 realized pnl",()=>assert.equal(core.derivePortfolioStateFromLedger([...opening,buy,sell]).realizedPnL,732.5));
ok("16 dividend",()=>assert.equal(core.derivePortfolioStateFromLedger([...opening,ev("DIVIDEND","2026-01-02",{symbol:"0050",grossAmount:500})]).cash,100500));
ok("17 fee",()=>assert.equal(core.derivePortfolioStateFromLedger([...opening,ev("FEE","2026-01-02",{grossAmount:100})]).cash,99900));
ok("18 tax",()=>assert.equal(core.derivePortfolioStateFromLedger([...opening,ev("TAX","2026-01-02",{grossAmount:80})]).cash,99920));
ok("19 deposit",()=>assert.equal(core.derivePortfolioStateFromLedger([...opening,ev("DEPOSIT","2026-01-02",{grossAmount:1000})]).externalNetFlow,1000));
ok("20 withdrawal",()=>assert.equal(core.derivePortfolioStateFromLedger([...opening,ev("WITHDRAWAL","2026-01-02",{grossAmount:1000})]).externalNetFlow,-1000));
ok("21 chronological deterministic replay",()=>assert.deepEqual(core.derivePortfolioStateFromLedger([buy,...opening]).holdings,core.derivePortfolioStateFromLedger([...opening,buy]).holdings));
ok("22 same-day transactions stable by timestamp/id",()=>assert.deepEqual(core.sortEvents([sell,buy]).map(x=>x.type),["BUY","SELL"]));
ok("23 oversell blocked",()=>assert.equal(core.derivePortfolioStateFromLedger([...opening,ev("SELL","2026-01-02",{symbol:"0050",quantity:101,unitPrice:60})]).status,"OVERSELL"));
ok("24 negative cash buy blocked",()=>assert.equal(core.derivePortfolioStateFromLedger([ev("OPENING_CASH","2026-01-01",{grossAmount:10}),ev("BUY","2026-01-02",{symbol:"0050",quantity:1,unitPrice:20})]).status,"NEGATIVE_CASH"));
ok("25 excessive withdrawal blocked",()=>assert.equal(core.derivePortfolioStateFromLedger([ev("OPENING_CASH","2026-01-01",{grossAmount:10}),ev("WITHDRAWAL","2026-01-02",{grossAmount:20})]).status,"NEGATIVE_CASH"));
ok("26 invalid number",()=>assert.equal(core.normalizeEvent({type:"BUY",tradeDate:"2026-01-01",timestamp:ts("2026-01-01"),symbol:"0050",quantity:"x",unitPrice:1}),null));
ok("27 zero quantity",()=>assert.equal(core.normalizeEvent({type:"BUY",tradeDate:"2026-01-01",timestamp:ts("2026-01-01"),symbol:"0050",quantity:0,unitPrice:1}),null));
ok("28 negative quantity",()=>assert.equal(core.normalizeEvent({type:"BUY",tradeDate:"2026-01-01",timestamp:ts("2026-01-01"),symbol:"0050",quantity:-1,unitPrice:1}),null));
ok("29 malformed event",()=>assert.equal(core.normalizeEvent({hello:"world"}),null));
const validLedger=ledger([...opening,buy,sell]);
ok("30 invalid edit blocked atomically",()=>{const r=core.mutateLedger(validLedger,{type:"EDIT",id:buy.id,event:{...buy,quantity:10000}});assert(!r.ok);assert.equal(validLedger.events[2].quantity,100)});
ok("31 invalid delete blocked atomically",()=>{const r=core.mutateLedger(validLedger,{type:"DELETE",id:opening[0].id});assert(!r.ok);assert.equal(r.status,"NEGATIVE_CASH")});
const snaps=[{date:"2026-01-01",totalAssets:100},{date:"2026-01-02",totalAssets:110},{date:"2026-01-03",totalAssets:121}];
ok("32 TWR no cash flow",()=>assert(Math.abs(core.calculateTwr({snapshots:snaps}).value-21)<1e-8));
ok("33 TWR deposit excluded with EOD timing",()=>assert(Math.abs(core.calculateTwr({snapshots:[{date:"2026-01-01",totalAssets:100},{date:"2026-01-02",totalAssets:160}],events:[ev("DEPOSIT","2026-01-02",{grossAmount:50})]}).value-10)<1e-8));
ok("34 TWR withdrawal excluded",()=>assert(Math.abs(core.calculateTwr({snapshots:[{date:"2026-01-01",totalAssets:100},{date:"2026-01-02",totalAssets:60}],events:[ev("WITHDRAWAL","2026-01-02",{grossAmount:50})]}).value-10)<1e-8));
ok("35 buy is internal",()=>assert(Math.abs(core.calculateTwr({snapshots:snaps.slice(0,2),events:[buy]}).value-10)<1e-8));
ok("36 sell is internal",()=>assert(Math.abs(core.calculateTwr({snapshots:snaps.slice(0,2),events:[sell]}).value-10)<1e-8));
ok("37 dividend counts in portfolio return",()=>assert(Math.abs(core.calculateTwr({snapshots:[{date:"2026-01-01",totalAssets:100},{date:"2026-01-02",totalAssets:105}],events:[ev("DIVIDEND","2026-01-02",{symbol:"0050",grossAmount:5})]}).value-5)<1e-8));
ok("38 fee reduces portfolio return",()=>assert(Math.abs(core.calculateTwr({snapshots:[{date:"2026-01-01",totalAssets:100},{date:"2026-01-02",totalAssets:99}],events:[ev("FEE","2026-01-02",{grossAmount:1})]}).value+1)<1e-8));
ok("39 opening baseline is not external flow",()=>assert(Math.abs(core.calculateTwr({snapshots:snaps.slice(0,2),events:opening}).value-10)<1e-8));
ok("40 selected period",()=>assert.equal(core.calculateTwr({snapshots:[{date:"2025-01-01",totalAssets:50},...snaps],period:"1M"}).observations,3));
ok("41 insufficient TWR data",()=>assert.equal(core.calculateTwr({snapshots:snaps.slice(0,1)}).status,"INSUFFICIENT_HISTORY"));
ok("42 simple one-year XIRR",()=>assert(Math.abs(core.calculateXirr([{date:"2025-01-01",amount:-100},{date:"2026-01-01",amount:110}]).value-10)<.01));
ok("43 irregular dates XIRR",()=>assert(core.calculateXirr([{date:"2025-01-01",amount:-100},{date:"2025-06-01",amount:-20},{date:"2026-01-01",amount:130}]).available));
ok("44 multiple deposits XIRR",()=>assert(core.calculateXirr([{date:"2025-01-01",amount:-100},{date:"2025-03-01",amount:-30},{date:"2026-01-01",amount:150}]).available));
ok("45 withdrawal XIRR",()=>assert(core.calculateXirr([{date:"2025-01-01",amount:-100},{date:"2025-06-01",amount:20},{date:"2026-01-01",amount:100}]).available));
ok("46 terminal value included",()=>assert.equal(core.buildXirrCashFlows(migration,{date:"2026-12-31",value:999}).at(-1).amount,999));
ok("47 no valid root fail soft",()=>assert.equal(core.calculateXirr([{date:"2025-01-01",amount:10},{date:"2026-01-01",amount:20}]).status,"NO_ROOT"));
ok("48 convergence guard",()=>{const result=core.calculateXirr([{date:"2025-01-01",amount:-1},{date:"2026-01-01",amount:1e15},{date:"2027-01-01",amount:-1e15}]);assert(!result.available||result.iterations<=200)});
ok("49 same-day XIRR fail soft",()=>assert.doesNotThrow(()=>core.calculateXirr([{date:"2025-01-01",amount:-100},{date:"2025-01-01",amount:110}])));
ok("50 deterministic XIRR",()=>{const f=[{date:"2025-01-01",amount:-100},{date:"2026-01-01",amount:110}];assert.equal(core.calculateXirr(f).value,core.calculateXirr(f).value)});
const derived=core.derivePortfolioStateFromLedger(opening),snapshot={cash:100000,holdings:{"0050":{quantity:100,marketPrice:99,marketValue:9900}}};
ok("51 reconciliation match",()=>assert(core.reconcileLedgerWithSnapshot(derived,snapshot).match));
ok("52 quantity mismatch",()=>assert.equal(core.reconcileLedgerWithSnapshot(derived,{...snapshot,holdings:{"0050":{quantity:99}}}).status,"UNRECONCILED_STATE"));
ok("53 cash mismatch",()=>assert.equal(core.reconcileLedgerWithSnapshot(derived,{...snapshot,cash:99999}).status,"UNRECONCILED_STATE"));
ok("54 price-only change matches",()=>assert(core.reconcileLedgerWithSnapshot(derived,{...snapshot,holdings:{"0050":{quantity:100,marketPrice:1}}}).match));
ok("55 market value-only change matches",()=>assert(core.reconcileLedgerWithSnapshot(derived,{...snapshot,holdings:{"0050":{quantity:100,marketValue:1}}}).match));
ok("56 added symbol mismatch",()=>assert.equal(core.reconcileLedgerWithSnapshot(derived,{...snapshot,holdings:{...snapshot.holdings,"00830":{quantity:1}}}).status,"UNRECONCILED_STATE"));
ok("57 reconciliation fail-soft",()=>assert.equal(core.reconcileLedgerWithSnapshot(null,null).status,"UNAVAILABLE"));
ok("58 duplicate warning",()=>assert(core.detectLikelyDuplicate([buy],{...buy,id:""})));
ok("59 versioned ledger validation",()=>assert.equal(core.validateLedger(validLedger).version,core.VERSION));
ok("60 stable ids are not array indexes",()=>assert(/^pl_/.test(buy.id)));
const many=[ev("OPENING_CASH","2026-01-01",{grossAmount:1000000}),...Array.from({length:105},(_,i)=>core.normalizeEvent({type:i%2?"FEE":"DEPOSIT",tradeDate:"2026-01-02",timestamp:new Date(Date.parse("2026-01-02T00:00:00Z")+i*1000).toISOString(),createdAt:new Date(Date.parse("2026-01-02T00:00:00Z")+i*1000).toISOString(),grossAmount:1,source:"TEST"}))];
ok("61 100+ event ledger replays",()=>assert(core.derivePortfolioStateFromLedger(many).valid));
ok("62 transaction UI exists",()=>["portfolioTransactionModal","portfolioLedgerModal","portfolioLedgerMigrationModal"].forEach(id=>assert.match(html,new RegExp(`id="${id}"`))));
ok("63 recent transactions precede settings",()=>assert(html.indexOf("portfolioLedgerPanel")<html.indexOf('class="panel portfolioSettings"')));
ok("64 mobile recent list is capped at three",()=>assert.match(css,/portfolioLedgerRows \.portfolioLedgerRow:nth-child\(n\+4\)/));
ok("65 old backup stays supported",()=>assert.match(ui,/const imported = core\.validateImportPayload\(parsed\)/));
ok("66 new backup includes ledger and snapshots",()=>{assert.match(ui,/ledgerVersion:ledger\?\.version/);assert.match(ui,/snapshots:portfolioHistory/)});
ok("67 smart allocation uses derived cash",()=>assert.match(ui,/cash: ledgerState\?\.valid \? ledgerState\.cash/));
ok("68 opening position edit has second confirmation",()=>assert.match(ui,/修改期初部位會改變正式績效基準/));
ok("69 delete requires confirmation",()=>assert.match(ui,/刪除這筆.*confirm/));
ok("70 no server persistence added",()=>assert.doesNotMatch(ui,/\/api\/portfolio|portfolio.*POST/i));
console.log(`Portfolio Ledger Phase 4: ${passed}/${passed} PASS`);
