const assert=require("assert"),fs=require("fs"),path=require("path"),vm=require("vm");
const root=path.resolve(__dirname,".."),html=fs.readFileSync(path.join(root,"index.html"),"utf8"),css=fs.readFileSync(path.join(root,"formal-black-gold.css"),"utf8"),contract=require(path.join(root,"hs-decision-layer-v1.js"));
const start=html.indexOf("const RADAR_EVENT_WINDOW="),end=html.indexOf("function radarRangeBar",start),source=html.slice(start,end);
assert(start>0&&end>start,"Phase 10 builder source missing");
const symbols=["0050","00662","00757","00830","00935","009815"],names=Object.fromEntries(symbols.map(symbol=>[symbol,symbol]));
const context={Number,String,Math,Map,Set,Array,Date,Intl,Object,console,window:{HSDecisionLayerV1:contract},LONG_RADAR_CODES:new Set(symbols),RADAR_SCORE_LEVEL_VERSION:"HS_C4_LEVELS_V2",finalizedCoreScoreHistoryArtifact:null,researchC4HistoryArtifacts:new Map(),researchC4HistoryStatus:new Map(),$:()=>null,document:{querySelectorAll:()=>[]},showRadarDetail:()=>{},esc:value=>String(value),officialArtifactCoreScoreHistory:(artifact,ticker,limit=66)=>((artifact?.series?.[ticker]||[]).slice().sort((a,b)=>b.tradingDate.localeCompare(a.tradingDate)).slice(0,limit)),radarOverviewNextLevel:value=>{const score=Math.floor(Number(value)),nextThreshold=contract.NEXT_THRESHOLDS.find(threshold=>threshold>score);return nextThreshold===undefined?{available:true,isMaxLevel:true,nextThreshold:null,nextLabel:null,distance:0}:{available:true,isMaxLevel:false,nextThreshold,nextLabel:contract.STAGES.find(stage=>stage.min===nextThreshold).label,distance:nextThreshold-score}}};
vm.createContext(context);vm.runInContext(`${source}\nthis.api={build:buildRadarEvents,html:radarEventCenterHtml,group:radarEventGroupLabel};`,context);
const row=(date,score)=>({symbol:"00830",tradingDate:date,displayScore:score,dataAsOf:`${date}T13:30:00+08:00`}),artifact=scores=>({series:{"00830":scores.map((score,index)=>row(`2026-01-${String(index+1).padStart(2,"0")}`,score))}}),items=Object.entries(names).map(([id,name])=>({id,name}));
const build=(scores,extra={})=>context.api.build({items,finalizedArtifact:artifact(scores),researchArtifacts:new Map(),researchStatuses:new Map(),contract,limit:100,...extra});
const ofType=(events,type)=>events.filter(event=>event.event_type===type||event.event_types.includes(type));
for(const [before,after,label] of [[29,30,"回檔訊號出現"],[39,40,"加碼條件浮現"],[44,45,"試探加碼"],[49,50,"正式加碼訊號"]]){const event=ofType(build([before,after]),"CROSS_LEVEL")[0];assert(event&&event.title.includes(label),`${before} → ${after}`)}
let event=ofType(build([46,43]),"CROSS_LEVEL")[0];assert.equal(event.title,'由「試探加碼」回到「加碼條件浮現」');
let events=ofType(build([37,38,39,39]),"NEXT_LEVEL");assert.deepEqual(events.map(event=>event.score_after).sort((a,b)=>a-b),[38,39],"same distance must not duplicate");
assert.equal(ofType(build([36,37,38]),"NEXT_LEVEL").at(-1).score_after,38,"distance 3 → 2 creates event");
assert.equal(ofType(build([20,20,20,20,20,29]),"FIVE_DAY_CHANGE").length,0,"5D +9 must not emit");
assert.equal(ofType(build([20,20,20,20,20,30]),"FIVE_DAY_CHANGE").length,1,"5D +10 must emit");
const research={records:Array.from({length:100},(_,index)=>({display_score:index+1}))},percentile=(before,after,threshold)=>{const result=context.api.build({items,finalizedArtifact:artifact([before,after]),researchArtifacts:new Map([["00830",research]]),researchStatuses:new Map([["00830","READY"]]),contract,limit:100});const hit=ofType(result,"HISTORICAL_PERCENTILE").find(item=>item.title.includes(`P${threshold}`));assert(hit,`P${threshold} crossing`)};
percentile(84,85,85);percentile(89,90,90);percentile(94,95,95);
events=context.api.build({items,finalizedArtifact:artifact([84,85,85]),researchArtifacts:new Map([["00830",research]]),researchStatuses:new Map([["00830","READY"]]),contract,limit:100});assert.equal(ofType(events,"HISTORICAL_PERCENTILE").length,1,"same percentile must not duplicate");
const diagnostics=[{symbol:"00830",date:"2026-01-01",timestamp:"2026-01-01T13:30:00+08:00",status:"HEALTHY"},{symbol:"00830",date:"2026-01-02",timestamp:"2026-01-02T13:30:00+08:00",status:"STALE",reason:"FINALIZED 過期"},{symbol:"00830",date:"2026-01-03",timestamp:"2026-01-03T13:30:00+08:00",status:"STALE",reason:"FINALIZED 過期"},{symbol:"00830",date:"2026-01-04",timestamp:"2026-01-04T13:30:00+08:00",status:"HEALTHY"}];
events=context.api.build({items,finalizedArtifact:{series:{}},diagnostics,contract,limit:100});assert.equal(ofType(events,"DATA_STATUS").length,2);assert(ofType(events,"DATA_STATUS").some(item=>item.title==="資料狀態異常"));assert(ofType(events,"DATA_STATUS").some(item=>item.title==="資料狀態已恢復"));
events=context.api.build({items,finalizedArtifact:{series:{}},diagnostics:[{symbol:"009815",date:"2026-01-01",status:"HEALTHY"},{symbol:"009815",date:"2026-01-02",status:"STALE",reason:"原生資料缺失"}],researchArtifacts:new Map(),researchStatuses:new Map(),contract,limit:100});assert.equal(ofType(events,"HISTORICAL_PERCENTILE").length,0);assert.equal(ofType(events,"DATA_STATUS").length,1,"009815 can still build non-percentile events");
const input={items,finalizedArtifact:artifact([20,30,40,50,60,70,80]),researchArtifacts:new Map(),researchStatuses:new Map(),diagnostics,contract,limit:100};assert.equal(JSON.stringify(context.api.build(input)),JSON.stringify(context.api.build(input)),"builder must be deterministic");
const manyScores=Array.from({length:60},(_,index)=>index%2?20:50);assert.equal(context.api.build({items,finalizedArtifact:artifact(manyScores),contract,limit:20}).length,20,"max 20 events");
assert.match(html,/data-radar-events-phase="10"/);assert.match(html,/data-radar-event-filter="ALL"[^>]+aria-pressed="true"/);assert.match(html,/class="radarEventItem"[^>]+data-open-radar-detail/);assert.match(html,/20260919-radar-events-phase10/);assert.match(css,/\.radarEventFilters button\{[^}]*min-height:44px/);assert.match(css,/@media\(max-width:430px\)[\s\S]*\.radarEventItem\{/);
const production=JSON.parse(fs.readFileSync(path.join(root,"finalized-core-score-snapshots-v1.json"),"utf8")),productionSeries=Object.fromEntries(symbols.map(symbol=>[symbol,[]]));
for(const snapshot of production.snapshots||[])for(const symbol of symbols){const item=(snapshot.rows||[]).find(value=>value.symbol===symbol),score=Number(item?.final_core_score);if(snapshot.snapshot_type==="FINALIZED_CLOSE"&&snapshot.finalized===true&&Number.isFinite(score)&&item?.status!=="WAIT_NATIVE")productionSeries[symbol].push({symbol,tradingDate:snapshot.date,displayScore:Math.floor(score),dataAsOf:item.data_as_of||snapshot.finalized_at})}
const productionResearch=new Map(),productionStatuses=new Map();for(const symbol of symbols){const file=path.join(root,"research","c4_historical",`${symbol}.json`);if(fs.existsSync(file)){productionResearch.set(symbol,JSON.parse(fs.readFileSync(file,"utf8")));productionStatuses.set(symbol,"READY")}}
const productionEvents=context.api.build({items,finalizedArtifact:{series:productionSeries},researchArtifacts:productionResearch,researchStatuses:productionStatuses,contract,limit:20});assert.equal(new Set(productionEvents.map(item=>item.event_id)).size,productionEvents.length);console.log("CURRENT_PRODUCTION_EVENTS",JSON.stringify(productionEvents.map(item=>({date:item.date,etf:item.etf,type:item.event_type,title:item.title,description:item.description}))));
console.log("PASS Phase 10 Event Center: 20 deterministic/dedup/accessibility contracts");
