const assert=require("assert"),fs=require("fs"),path=require("path"),vm=require("vm"),{execFileSync}=require("child_process");
const root=path.join(__dirname,".."),html=fs.readFileSync(path.join(root,"index.html"),"utf8"),css=fs.readFileSync(path.join(root,"formal-black-gold.css"),"utf8");
const start=html.indexOf("const DECISION_CENTER_HEALTH_LEVELS="),end=html.indexOf("function decisionCenterDistanceText",start);assert.ok(start>0&&end>start,"Phase 5 health helpers must exist");
const freshness=require(path.join(root,"data-freshness-core.js")),decision=require(path.join(root,"hs-decision-layer-v1.js")),core=require(path.join(root,"final-core-production.js"));
const context={window:{HSDataFreshnessCore:freshness},Intl,Date,Math,Number,String,Array,Map,Set,Object,esc:value=>String(value),taipeiToday:()=>"2026-09-07",LONG_TERM_CORE_SCORE_VERSION:"FINAL_CORE_WEIGHT_V1",LONG_RADAR_SCORED_CODES:new Set(["0050","00662","00757","00830","00935"])};vm.createContext(context);vm.runInContext(html.slice(start,end),context);
const symbols=["0050","00662","00757","00830","00935"],officialRows=symbols.map((symbol,index)=>({symbol,score:50-index,displayScore:50-index,date:"2026-09-04",tier:"正式加碼訊號"}));
function dual(market_state="HOLIDAY"){return{market_state,target_date:"2026-09-07",score_version:"FINAL_CORE_WEIGHT_V1",official_snapshot:{schema_version:1,snapshot_type:"FINALIZED_CLOSE",status:"SUCCESS",source_status:"FINALIZED_EOD",trading_date:"2026-09-04"},items:Object.fromEntries(symbols.map(symbol=>[symbol,{score_version:"FINAL_CORE_WEIGHT_V1",official:{status:"FINALIZED"},live:{display_eligible:false,freshness:"UNAVAILABLE",status:"UNAVAILABLE",trading_date:"2026-09-07"}}]))};}
function history(count=2){return new Map(symbols.map(symbol=>[symbol,{status:"READY",currentVersion:"FINAL_CORE_WEIGHT_V1",rows:count===1?[{date:"2026-09-04"}]:[{date:"2026-09-03"},{date:"2026-09-04"}]}]));}
function input(overrides={}){return{dualTrack:dual(),officialRows,historyBySymbol:history(),leverageState:{available:true,status:"STANDBY"},cnnSnapshot:{status:"LATEST",data_date:"2026-09-04"},forwardState:{available:true,status:"READY",detail:"功能可用"},adHocState:{available:true},targetDate:"2026-09-07",now:new Date("2026-09-06T02:00:00Z"),...overrides};}
let result=context.decisionCenterSystemHealth(input());assert.equal(result.level,"HEALTHY");assert.equal(result.items.find(x=>x.key==="live").status,"今日休市");console.log("A PASS: weekend without LIVE is not a warning");
const open=dual("OPEN");result=context.decisionCenterSystemHealth(input({dualTrack:open,now:new Date("2026-09-07T02:00:00Z")}));assert.equal(result.level,"WARNING");assert.equal(result.items.find(x=>x.key==="live").level,"WARNING");console.log("B PASS: OPEN plus stale/unavailable LIVE is WARNING");
result=context.decisionCenterSystemHealth(input());assert.equal(result.items.find(x=>x.key==="official").level,"HEALTHY");assert.equal(result.officialDate,"2026-09-04");console.log("C PASS: valid FINALIZED official source is HEALTHY");
result=context.decisionCenterSystemHealth(input({officialRows:officialRows.slice(1)}));assert.equal(result.level,"ERROR");assert.equal(result.items[0].level,"ERROR");console.log("D PASS: invalid/incomplete Official is ERROR");
result=context.decisionCenterSystemHealth(input({cnnSnapshot:{status:"STALE",data_date:"2026-08-28"}}));assert.equal(result.level,"WARNING");assert.equal(result.items[0].level,"HEALTHY");assert.equal(result.items.find(x=>x.key==="cnn").unaffected,"正式 C4");console.log("E PASS: stale CNN warns without invalidating Official C4");
const frozenDual=dual();const before=JSON.stringify(frozenDual);result=context.decisionCenterSystemHealth(input({dualTrack:frozenDual,forwardState:{available:false,status:"FAIL_CLOSED"}}));assert.equal(result.items.find(x=>x.key==="forward").level,"WARNING");assert.equal(JSON.stringify(frozenDual),before);console.log("F PASS: Forward issue is isolated and read-only");
const leverage={available:false,status:"DATA_UNAVAILABLE"},leverageBefore=JSON.stringify(leverage);result=context.decisionCenterSystemHealth(input({leverageState:leverage}));assert.equal(result.items.find(x=>x.key==="leverage").level,"WARNING");assert.equal(JSON.stringify(leverage),leverageBefore);console.log("G PASS: 00631L issue does not mutate strategy state");
result=context.decisionCenterSystemHealth(input({historyBySymbol:history(1)}));assert.equal(result.items.find(x=>x.key==="history").level,"WARNING");assert.equal(result.items[0].level,"HEALTHY");console.log("H PASS: insufficient history does not alter current Official");
result=context.decisionCenterSystemHealth(input({adHocState:{available:false}}));assert.equal(result.items.find(x=>x.key==="adhoc").level,"WARNING");assert.equal(result.items[0].level,"HEALTHY");console.log("I PASS: AD_HOC issue cannot contaminate Formal health");
assert.equal(context.decisionCenterSystemHealth(input()).label,"資料正常 ✓");assert.equal(context.decisionCenterSystemHealth(input({cnnSnapshot:{status:"STALE"}})).label,"資料注意 ⚠");assert.equal(context.decisionCenterSystemHealth(input({officialRows:[]})).label,"資料異常 ✕");console.log("J PASS: severity aggregation is deterministic");
const helperSource=html.slice(start,end);assert.doesNotMatch(helperSource,/calculateFinalCore|buildFinal\(|buildAdHocScore\(|localStorage|setItem|appendForward|fetch\(/);console.log("K PASS: health helpers do not recompute or write C4");
const protectedFiles=["backtest/long-term/final-core-score-v1.js","final-core-production.js","canonical-score-resolver.js","finalized-core-score-snapshots-v1.json","intraday-core-snapshots-v1.json","leverage-v1-core.js","hs-decision-layer-v1.js","persistence-core.js"];for(const file of protectedFiles)assert.equal(execFileSync("git",["diff","--name-only","HEAD","--",file],{cwd:root,encoding:"utf8"}).trim(),"",`${file} must remain unchanged from HEAD`);console.log("L PASS: protected surfaces are unchanged from HEAD");
assert.equal(context.LONG_RADAR_SCORED_CODES.has("009815"),false);assert.doesNotMatch(helperSource,/009815/);console.log("M PASS: 009815 WAIT_NATIVE remains outside Formal health");
assert.deepStrictEqual([...context.LONG_RADAR_SCORED_CODES],symbols);console.log("N PASS: Formal Eligible Universe is unchanged");
assert.equal(core.labelFor(50.2463).label,"正式加碼訊號");assert.equal(decision.interpret({symbol:"00830",score:50.2463,sourceStatus:"SUCCESS"}).decision_label_zh,"小額加碼");console.log("TIER AUDIT: canonical label=正式加碼訊號; Decision Layer label=小額加碼; thresholds unchanged");
assert.match(html,/資料健康 <small>SYSTEM HEALTH<\/small>/);assert.match(html,/影響：/);assert.match(html,/不影響：/);assert.match(html,/資料健康只讀取、驗證與顯示/);assert.match(css,/\.hsSystemHealthCard/);assert.match(css,/@media\(max-width:390px\)[\s\S]*\.hsSystemHealthDetail/);console.log("UI PASS: compact summary, Chinese-first detail and mobile guards exist");
