const assert=require("node:assert/strict"),ui=require("../personal-capital-ui-core.js");let passed=0;function test(name,fn){fn();passed++;process.stdout.write(`PASS ${name}\n`)}
function ready({symbol="0050",actual=60,target=64,score=55,action="ALLOW_ADD"}={}){return{symbol,status:"READY",action,allocation:{actualWeightPct:actual,targetAllocationPct:target,gapPct:target-actual},market:{score,scoreBucket:"SMALL_ADD",stage:{label:"分批加碼區"}},asOf:{decisionMode:"FORMAL",radarDate:"2026-08-21",aligned:true}}}
test("underweight action is human-readable",()=>assert.match(ui.renderHtml(ready()),/可加碼/));
test("priority and high priority actions are human-readable",()=>{assert.match(ui.renderHtml(ready({score:68,action:"PRIORITY_ADD"})),/優先加碼/);assert.match(ui.renderHtml(ready({symbol:"00830",actual:50,target:60,score:70,action:"HIGH_PRIORITY_ADD"})),/高優先加碼/)});
test("overweight on-target and wait actions render",()=>{assert.match(ui.renderHtml(ready({actual:65,target:60,action:"DO_NOT_ADD"})),/暫不加碼/);assert.match(ui.renderHtml(ready({actual:60,target:60,score:30,action:"HOLD"})),/維持配置/);assert.match(ui.renderHtml(ready({actual:55,target:60,score:30,action:"WAIT"})),/等待買點/)});
test("allocation and Core context render",()=>{const html=ui.renderHtml(ready({actual:55,target:60}));assert.match(html,/目前 55.0%/);assert.match(html,/低配 5.0%/);assert.match(html,/Core 55.0/)});
test("data unavailable never renders old action",()=>{const html=ui.renderHtml({status:"DATA_UNAVAILABLE",reasons:["PORTFOLIO_QUOTE_STALE"],asOf:{}});assert.match(html,/資料不足/);assert.match(html,/持股行情已過期/);assert.doesNotMatch(html,/data-capital-action/)});
test("missing target radar stale mismatch and 009815 coverage remain unavailable",()=>["TARGET_ALLOCATION_MISSING","RADAR_STALE","ASOF_MISMATCH","RADAR_COVERAGE_INSUFFICIENT"].forEach(reason=>assert.doesNotMatch(ui.renderHtml({status:"DATA_UNAVAILABLE",reasons:[reason],asOf:{}}),/data-capital-action/)));
test("presentation contains no score or valuation calculation",()=>{const fs=require("node:fs"),source=fs.readFileSync(require.resolve("../personal-capital-ui-core.js"),"utf8");assert.doesNotMatch(source,/longTermDecision\s*\(|calculatePortfolio\s*\(|scoreModel\s*\(/)});
test("integration reuses adapters and restricts the rendered scope",()=>{const fs=require("node:fs"),source=fs.readFileSync(require.resolve("../personal-capital-ui.js"),"utf8");assert.match(source,/inputCore\.normalizeSymbol/);assert.match(source,/policyCore\.evaluate/);assert.match(source,/\["0050","00662","00830","00935","009815"\]/);assert.doesNotMatch(source,/calculatePortfolio\s*\(|longTermDecision\s*\(/)});
process.stdout.write(`PASS ${passed} focused personal-capital UI tests\n`);
