"use strict";
const assert=require("node:assert/strict");
const fs=require("node:fs");
const view=require("../leverage-state-view.js");
const html=fs.readFileSync("index.html","utf8");
const css=fs.readFileSync("formal-black-gold.css","utf8");
const snapshot=JSON.parse(fs.readFileSync("00631l-leverage-status-v1.json","utf8"));
const rows=Array.from({length:420},(_,i)=>({date:new Date(Date.UTC(2024,0,1+i)).toISOString().slice(0,10),close:100-i*.08,low:99.5-i*.08,high:100.5-i*.08}));
assert.equal(view.deepDrop(rows).date,rows.at(-1).date);
assert.ok(view.deepDrop(rows).p120.percentile>=0);
assert.equal(view.deepDrop(rows.slice(0,120)).p120.percentile,null);
assert.equal(view.riskContraction(rows).checks.length,4);
assert.equal(view.riskContraction(rows.slice(0,10)).label,"資料不足");
const sample={...snapshot,price:{...snapshot.price,stale_after:"2099-01-01T16:30:00+08:00"}};
assert.equal(view.officialStatus(sample),sample);
assert.equal(view.officialStatus(snapshot,Date.parse(snapshot.price.stale_after)+1).price.freshness,"STALE");
assert.equal(view.officialStatus({...snapshot,symbol:"0050"}),null);
assert.equal(view.officialStatus({...snapshot,price:{...snapshot.price,freshness:"UNKNOWN_BAD"}}),null);
const current=view.renderHtml({officialRows:rows},sample,null);
assert.match(current,/00631L 槓桿狀態判讀/);
assert.match(current,/深跌程度 × V1 Shadow × 風險收斂/);
assert.match(current,/Shadow 尚未更新/);
assert.match(current,/Forward observations<\/dt><dd>0/);
assert.match(current,/最新完成日線<\/dt><dd>2026-09-24/);
assert.doesNotMatch(current,/2026-08-24/);
const evaluated={...sample,shadow:{...sample.shadow,latest_evaluation_date:sample.price.latest_completed_bar,triggered:false}};
const alignedRows=[...rows.slice(0,-1),{...rows.at(-1),date:sample.price.latest_completed_bar}];
const evaluatedHtml=view.renderHtml({officialRows:alignedRows},evaluated,alignedRows);
assert.match(evaluatedHtml,/未觸發/);
assert.doesNotMatch(evaluatedHtml,/Shadow 尚未更新/);
const unavailable=view.renderHtml({officialRows:rows},null,null);
assert.match(unavailable,/正式狀態 snapshot 不可用/);
assert.match(unavailable,/<strong>正式狀態資料不足<\/strong>/);
assert.match(html,/fetch\("00631l-leverage-status-v1\.json",\{cache:"no-store"\}\)/);
assert.doesNotMatch(html,/fetch\("research\/hs_leverage\/phase_l7_forward_policy\.json"/);
assert.match(html,/leverageStateJudgementHtml\(x\)/);
assert.match(css,/\.leverageStateGrid\{display:grid;grid-template-columns:repeat\(3,minmax\(0,1fr\)\)/);
assert.match(css,/@media\(max-width:700px\)\{\.leverageStateReading.*?\.leverageStateGrid\{grid-template-columns:minmax\(0,1fr\)/);
for(const phrase of ["建議買進","建議加碼","適合進場","抄底機會","勝率很高"])assert.doesNotMatch(current,new RegExp(phrase));
console.log("PASS 00631L official snapshot and three-layer UI");
