const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const root = path.join(__dirname, "..");
const html = fs.readFileSync(path.join(root, "index.html"), "utf8");
const portfolio = fs.readFileSync(path.join(root, "portfolio-v6.js"), "utf8");
const css = fs.readFileSync(path.join(root, "portfolio-v6.css"), "utf8");
const updater = fs.readFileSync(path.join(root, "scripts", "update_margin_data.py"), "utf8");

assert.match(html, /HS \| ETF股市雷達 v6\.2/);
assert.match(html, /marginBalanceCard/);
assert.match(html, /融資融券餘額/);
assert.match(html, /HSMarginRiskCore\.displayValues\(risk\)/);
assert.match(portfolio, /HSMarginRiskCore\.displayValues\(marginRisk\)/);
assert.match(portfolio, /擔保品/);
assert.match(css, /\.marginBalanceCard/);
assert.match(css, /border-radius:24px/);
assert.doesNotMatch(css, /\.marginRiskGrid/);
assert.doesNotMatch(html, /FinMind 市場融資金額/);
assert.doesNotMatch(updater, /MarginPurchaseMoney/);
assert.doesNotMatch(html + portfolio, /221\.33/);
assert.match(html, /市場推估融資維持率僅用於觀察整體融資戶壓力/);
assert.match(html, /查看 FOMO、推估方法、缺漏與資料來源/);
console.log("v6.2 rolling margin integration tests passed");
