"use strict";
const assert=require("node:assert/strict");
const fs=require("node:fs");
const path=require("node:path");
const root=path.resolve(__dirname,"..");
const html=fs.readFileSync(path.join(root,"index.html"),"utf8");
const css=fs.readFileSync(path.join(root,"formal-black-gold.css"),"utf8");

assert.match(html,/function radarScoreTrendHtml\(ticker,history=loadDailyLongRankHistory\(\)\)/);
assert.match(html,/coreScoreHistoryState\(ticker,history\)/);
assert.match(html,/latest\.displayScore/);
assert.match(html,/summaryDelta/);
assert.match(html,/latestScore-oldestScore/);
assert.match(html,/最新\$\{historyLabel\} \$\{latestScore\}/);
assert.match(html,/近 \$\{chronological\.length\} 筆/);
assert.match(html,/距 \$\{next\.value\} 還差/);
assert.match(html,/已進入極端區/);
assert.match(html,/40 回檔/);
assert.match(html,/50 小額/);
assert.match(html,/65 分批/);
assert.match(html,/80 罕見/);
assert.match(html,/value:70,label:"70 深跌"/);
assert.match(html,/value:90,label:"90 極端"/);
assert.match(html,/radarTrendScoreLabel/);
assert.match(html,/radarTrendPoint\$\{latestClass\}/);
assert.match(html,/role="img" aria-label="\$\{esc\(aria\)\}"/);
assert.match(html,/盤中 Core 不納入此趨勢/);
assert.match(html,/已累積 \$\{chronological\.length\} \/ 10 筆\$\{seriesHistoryLabel\}紀錄/);
assert.match(html,/正式盤後優先／本機盤後補充紀錄/);
assert.match(html,/本機盤後試算紀錄/);
assert.match(css,/\.radarTrendGuides \.is-secondary\{display:none\}/);
assert.match(css,/\.radarTrendPoint\.latest circle/);
assert.match(css,/\.radarTrendSummary/);
assert.match(css,/\.radarTrendScoreLabel/);
assert.match(css,/@media\(max-width:430px\)[\s\S]*\.radarTrendSummary/);
console.log("PASS ETF Radar V2.2 SCORE TREND readability contract");
