const assert=require("assert"),fs=require("fs"),path=require("path");
const root=path.resolve(__dirname,".."),engine=require(path.join(root,"radar-alert-rules-v1.js")),contract=require(path.join(root,"hs-decision-layer-v1.js"));
const html=fs.readFileSync(path.join(root,"index.html"),"utf8"),css=fs.readFileSync(path.join(root,"formal-black-gold.css"),"utf8"),source=fs.readFileSync(path.join(root,"radar-alert-rules-v1.js"),"utf8");
let passed=0;const test=(name,fn)=>{fn();passed++;console.log(`PASS ${name}`)},row=(date,score)=>({tradingDate:date,displayScore:score,historySource:"official"});
const memory=initial=>{const map=new Map(Object.entries(initial||{}));return{getItem:key=>map.has(key)?map.get(key):null,setItem:(key,value)=>map.set(key,value),removeItem:key=>map.delete(key),map}};
function step({state=engine.defaultState(),symbol="00830",date="2026-09-18",score=30,previousScore=29,rules=engine.defaultRuleSet(),percentileCurrent=null,percentilePrevious=null,diagnosticCurrent=null,diagnosticPrevious=null}){return engine.evaluateRadarAlerts({symbol,current:row(date,score),previous:row("2026-09-17",previousScore),percentileCurrent,percentilePrevious,diagnosticCurrent,diagnosticPrevious,resolvedRules:rules,existingAlertState:state,contract})}
function baseline(score=29,rules=engine.defaultRuleSet(),extra={}){return step({date:"2026-09-17",score,previousScore:score,rules,...extra}).next_alert_state}

test("versioned defaults and keys",()=>{assert.equal(engine.PREFERENCES_KEY,"HS_RADAR_ALERT_RULES_V1");assert.equal(engine.STATE_KEY,"HS_RADAR_ALERT_STATE_V1");assert.equal(engine.defaultPreferences().global.cross_level,true)});
test("global inheritance",()=>{const prefs=engine.defaultPreferences();prefs.global.distance=2;assert.equal(engine.resolveRules(prefs,"0050").distance,2)});
test("ETF custom override",()=>{const prefs=engine.defaultPreferences();prefs.etfs["00830"]={mode:"custom",rules:{...prefs.global,distance:1}};assert.equal(engine.resolveRules(prefs,"00830").distance,1);assert.equal(engine.resolveRules(prefs,"0050").distance,0)});
test("upward cross-level",()=>{const result=step({state:baseline(29),score:30,previousScore:29});assert.equal(result.candidate_alerts[0].rule_type,"CROSS_LEVEL")});
test("39 to 40 cross-level",()=>{const result=step({state:baseline(39),score:40,previousScore:39});assert(result.candidate_alerts.some(alert=>alert.rule_type==="CROSS_LEVEL"))});
test("49 to 50 cross-level",()=>{const result=step({state:baseline(49),score:50,previousScore:49});assert(result.candidate_alerts.some(alert=>alert.rule_type==="CROSS_LEVEL"))});
test("downward cross-level",()=>{const result=step({state:baseline(30),score:29,previousScore:30});assert.equal(result.candidate_alerts[0].rule_type,"CROSS_LEVEL")});
test("downward cross can be disabled",()=>{const rules={...engine.defaultRuleSet(),downward_cross:false};assert.equal(step({state:baseline(30,rules),score:29,previousScore:30,rules}).candidate_alerts.length,0)});
test("score threshold crossing",()=>{const rules={...engine.defaultRuleSet(),score_enabled:true,score_threshold:50};const result=step({state:baseline(49,rules),score:50,previousScore:49,rules});assert(result.candidate_alerts.some(alert=>alert.rule_type==="SCORE_THRESHOLD"))});
test("score threshold has no duplicate while above",()=>{const rules={...engine.defaultRuleSet(),score_enabled:true,score_threshold:50},first=step({state:baseline(49,rules),score:50,previousScore:49,rules}),second=step({state:first.next_alert_state,date:"2026-09-19",score:51,previousScore:50,rules});assert(!second.candidate_alerts.some(alert=>alert.rule_type==="SCORE_THRESHOLD"))});
test("score threshold re-arms after leaving",()=>{const rules={...engine.defaultRuleSet(),score_enabled:true,score_threshold:50};let state=step({state:baseline(49,rules),score:50,previousScore:49,rules}).next_alert_state;state=step({state,date:"2026-09-19",score:49,previousScore:50,rules}).next_alert_state;const again=step({state,date:"2026-09-20",score:50,previousScore:49,rules});assert(again.candidate_alerts.some(alert=>alert.rule_type==="SCORE_THRESHOLD"))});
test("next-level distance enters once",()=>{const rules={...engine.defaultRuleSet(),distance:2};const result=step({state:baseline(42,rules),score:43,previousScore:42,rules});assert(result.candidate_alerts.some(alert=>alert.rule_type==="NEXT_LEVEL"))});
test("next-level distance does not repeat in zone",()=>{const rules={...engine.defaultRuleSet(),distance:2};let state=step({state:baseline(42,rules),score:43,previousScore:42,rules}).next_alert_state;const result=step({state,date:"2026-09-19",score:44,previousScore:43,rules});assert(!result.candidate_alerts.some(alert=>alert.rule_type==="NEXT_LEVEL"))});
test("next-level distance re-arms",()=>{const rules={...engine.defaultRuleSet(),distance:2};let state=step({state:baseline(42,rules),score:43,previousScore:42,rules}).next_alert_state;state=step({state,date:"2026-09-19",score:41,previousScore:43,rules}).next_alert_state;const result=step({state,date:"2026-09-20",score:43,previousScore:41,rules});assert(result.candidate_alerts.some(alert=>alert.rule_type==="NEXT_LEVEL"))});
test("historical percentile crossing",()=>{const rules={...engine.defaultRuleSet(),percentile_enabled:true,percentiles:[85]};const result=step({state:baseline(40,rules,{percentileCurrent:84}),score:41,previousScore:40,rules,percentilePrevious:84,percentileCurrent:85});assert(result.candidate_alerts.some(alert=>alert.rule_type==="HISTORICAL_PERCENTILE"))});
test("percentile does not repeat above threshold",()=>{const rules={...engine.defaultRuleSet(),percentile_enabled:true,percentiles:[85]};let state=step({state:baseline(40,rules,{percentileCurrent:84}),score:41,previousScore:40,rules,percentilePrevious:84,percentileCurrent:85}).next_alert_state;const result=step({state,date:"2026-09-19",score:42,previousScore:41,rules,percentilePrevious:85,percentileCurrent:86});assert(!result.candidate_alerts.some(alert=>alert.rule_type==="HISTORICAL_PERCENTILE"))});
test("percentile re-arms after leaving",()=>{const rules={...engine.defaultRuleSet(),percentile_enabled:true,percentiles:[85]};let state=step({state:baseline(40,rules,{percentileCurrent:84}),score:41,previousScore:40,rules,percentilePrevious:84,percentileCurrent:85}).next_alert_state;state=step({state,date:"2026-09-19",score:40,previousScore:41,rules,percentilePrevious:86,percentileCurrent:84}).next_alert_state;const result=step({state,date:"2026-09-20",score:42,previousScore:40,rules,percentilePrevious:84,percentileCurrent:86});assert(result.candidate_alerts.some(alert=>alert.rule_type==="HISTORICAL_PERCENTILE"))});
test("P84 to P91 emits only highest applicable percentile",()=>{const rules={...engine.defaultRuleSet(),percentile_enabled:true,percentiles:[85,90,95]};const result=step({state:baseline(40,rules,{percentileCurrent:84}),score:50,previousScore:40,rules,percentilePrevious:84,percentileCurrent:91});const alerts=result.candidate_alerts.filter(alert=>alert.rule_type==="HISTORICAL_PERCENTILE");assert.equal(alerts.length,1);assert.equal(alerts[0].threshold,90);assert.deepEqual(alerts[0].metadata.crossed,[85,90])});
test("highest percentile only on multi-cross",()=>{const rules={...engine.defaultRuleSet(),percentile_enabled:true,percentiles:[85,90,95]};const result=step({state:baseline(40,rules,{percentileCurrent:84}),score:50,previousScore:40,rules,percentilePrevious:84,percentileCurrent:96});const alerts=result.candidate_alerts.filter(alert=>alert.rule_type==="HISTORICAL_PERCENTILE");assert.equal(alerts.length,1);assert.equal(alerts[0].threshold,95)});
test("research alert requires supplied valid percentile",()=>{const rules={...engine.defaultRuleSet(),percentile_enabled:true,percentiles:[85]};const result=step({state:baseline(40,rules),symbol:"009815",score:50,previousScore:40,rules});assert(!result.candidate_alerts.some(alert=>alert.rule_type==="HISTORICAL_PERCENTILE"))});
test("data unhealthy transition",()=>{const state=baseline(40,engine.defaultRuleSet(),{diagnosticCurrent:{status:"HEALTHY"}}),result=step({state,score:40,previousScore:40,diagnosticPrevious:{status:"HEALTHY"},diagnosticCurrent:{status:"FAILED",reason:"INTEGRITY_FAILED"}});assert(result.candidate_alerts.some(alert=>alert.rule_type==="DATA_STATUS"&&alert.priority==="HIGH"))});
test("stale to stale does not duplicate",()=>{const state=baseline(40,engine.defaultRuleSet(),{diagnosticCurrent:{status:"STALE"}}),result=step({state,score:40,previousScore:40,diagnosticPrevious:{status:"STALE"},diagnosticCurrent:{status:"STALE"}});assert(!result.candidate_alerts.some(alert=>alert.rule_type==="DATA_STATUS"))});
test("data recovery transition",()=>{const state=baseline(40,engine.defaultRuleSet(),{diagnosticCurrent:{status:"FAILED"}}),result=step({state,score:40,previousScore:40,diagnosticPrevious:{status:"FAILED"},diagnosticCurrent:{status:"HEALTHY"}});assert(result.candidate_alerts.some(alert=>alert.rule_type==="DATA_STATUS"))});
test("first initialization creates no pending alerts",()=>{const result=step({score:90,previousScore:0});assert.equal(result.baseline,true);assert.equal(result.candidate_alerts.length,0);assert.equal(result.next_alert_state.pending_alerts.length,0)});
test("refresh same finalized date does not duplicate",()=>{const first=step({state:baseline(29),score:30,previousScore:29}),again=step({state:first.next_alert_state,score:30,previousScore:29});assert.equal(again.candidate_alerts.length,0)});
test("deterministic alert id",()=>{const a=step({state:baseline(29),score:30,previousScore:29}),b=step({state:baseline(29),score:30,previousScore:29});assert.deepEqual(a.candidate_alerts,b.candidate_alerts);assert.equal(a.next_alert_state.initialized_at,b.next_alert_state.initialized_at)});
test("bundles same ETF and date",()=>{const alerts=[{alert_id:"a",etf:"0050",trigger_date:"2026-09-18",title:"A",priority:"LOW"},{alert_id:"b",etf:"0050",trigger_date:"2026-09-18",title:"B",priority:"HIGH"}];const bundles=engine.bundleRadarAlerts(alerts);assert.equal(bundles.length,1);assert.equal(bundles[0].alerts.length,2)});
test("invalid preference version migrates to defaults",()=>{assert.deepEqual(engine.normalizePreferences({version:"OLD"}),engine.defaultPreferences())});
test("invalid state version migrates to empty baseline",()=>{assert.deepEqual(engine.normalizeState({version:"OLD",pending_alerts:[1]}),engine.defaultState())});
test("storage save load and reset",()=>{const storage=memory();let prefs=engine.defaultPreferences();prefs.global.distance=2;engine.savePreferences(storage,prefs);assert.equal(engine.loadPreferences(storage).global.distance,2);assert.equal(engine.resetPreferences(storage).global.distance,0)});
test("preview is historical reconstruction only",()=>{const rules={...engine.defaultRuleSet(),score_enabled:true,score_threshold:50},preview=engine.rebuildRadarAlertPreview({symbol:"00830",finalizedRows:[row("2026-09-17",49),row("2026-09-18",50)],resolvedRules:rules,contract});assert(preview.alerts.some(alert=>alert.source==="FINALIZED_CLOSE"));assert(preview.alerts.every(alert=>alert.trigger_date==="2026-09-18"))});
test("UI marker, accessibility and Phase 11A rule isolation",()=>{const rulesSource=fs.readFileSync(path.join(root,"radar-alert-rules-v1.js"),"utf8");assert(html.includes('data-radar-alerts-phase="11a"'));assert(html.includes("radar-alert-rules-v1.js?v=20260920-background-alert-cutover-phase11b2c"));assert(html.includes('role="switch"'));assert(html.includes('aria-live="polite"'));assert(!/Notification\s*\.|new\s+Notification|serviceWorker\.ready\.then\([^)]*pushManager/.test(rulesSource))});
test("mobile touch and one-column rules",()=>{assert(css.includes(".radarAlertRuleGrid{grid-template-columns:1fr}"));assert(css.includes("min-height:44px"));assert(css.includes("max-width:375px"))});

console.log(`Phase 11A alert rules: ${passed}/${passed} PASS`);
