"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),os=require("node:os"),path=require("node:path");
const ledger=require("../scripts/append_personal_capital_forward.js");
const temp=fs.mkdtempSync(path.join(os.tmpdir(),"pcfv1-test-")),ledgerPath=path.join(temp,"ledger.json");
const write=records=>fs.writeFileSync(ledgerPath,JSON.stringify({...ledger.defaultLedger("2026-08-24T15:53:12.601Z"),records}));
const ready=(symbol="0050",score=70,canonicalAsOfAt="2026-08-24T16:00:00.000Z")=>({version:"PERSONAL_CAPITAL_INPUT_V1",symbol,eligibility:"READY",reasons:[],portfolio:{actualWeightPct:40,targetAllocationPct:60},radar:{score,stage:{key:"add"},decisionMode:"FORMAL"},freshness:{portfolio:"CURRENT",radar:"CURRENT",sourceConflict:false},asOf:{portfolioDate:"2026-08-24",radarDate:"2026-08-24",decisionMode:"FORMAL",aligned:true,canonicalAsOfAt}});
const policy=(symbol="0050",score=70)=>({version:"PERSONAL_CAPITAL_POLICY_V1",symbol,status:"READY",allocation:{actualWeightPct:40,targetAllocationPct:60,gapPct:20,state:"DEEPLY_UNDERWEIGHT"},market:{score,stage:{key:"add"},scoreBucket:"DEEP_ADD",decisionMode:"FORMAL"},action:"HIGH_PRIORITY_ADD",rationaleCodes:["PORTFOLIO_DEEPLY_UNDERWEIGHT","MARKET_DEEP_ADD"],asOf:{}});
const unavailable=(symbol,reason,canonicalAsOfAt="2026-08-24T16:00:00.000Z")=>({version:"PERSONAL_CAPITAL_INPUT_V1",symbol,eligibility:"DATA_UNAVAILABLE",reasons:[reason],freshness:{portfolio:"STALE",radar:"CURRENT",sourceConflict:false},asOf:{portfolioDate:"2026-08-24",radarDate:"2026-08-24",decisionMode:"FORMAL",aligned:false,canonicalAsOfAt}});
const payload=({normalizedInput=ready(),policyResult=policy(),tradingDate="2026-08-24",observedAt="2026-08-24T23:55:00+08:00"}={})=>({observations:[{normalizedInput,policyResult,tradingDate,observedAt}]});
try{
  write([]);let result=ledger.appendObservations(ledgerPath,payload());assert.equal(result.appended,1,"first valid observation appends");assert.equal(fs.readdirSync(temp).some(name=>name.endsWith(".tmp")),false,"atomic write leaves no partial artifact");let rows=ledger.readLedger(ledgerPath).records;assert.equal(rows[0].previousHash,null);assert.equal(rows[0].recordHash,ledger.recordHash(rows[0]));assert.equal(rows[0].market.score,70);
  assert.equal(ledger.appendObservations(ledgerPath,payload()).results[0].status,"NOOP_IDENTICAL","retry is idempotent");assert.equal(ledger.readLedger(ledgerPath).records.length,1);
  assert.throws(()=>ledger.appendObservations(ledgerPath,payload({policyResult:policy("0050",71)})),/OBSERVATION_CONFLICT/,"same key changed content conflicts");
  result=ledger.appendObservations(ledgerPath,{observations:["00662","00830","00935","009815"].map((symbol,index)=>({normalizedInput:ready(symbol,65+index),policyResult:policy(symbol,65+index),tradingDate:"2026-08-24",observedAt:"2026-08-24T23:55:00+08:00"}))});assert.equal(result.appended,4,"multiple eligible symbols append");rows=ledger.readLedger(ledgerPath).records;assert.equal(rows.length,5);assert.doesNotThrow(()=>ledger.verifyChain(rows));assert.equal(rows[1].previousHash,rows[0].recordHash);
  const before=JSON.stringify(rows[0]);const unavailablePolicy={version:"PERSONAL_CAPITAL_POLICY_V1",symbol:"009815",status:"DATA_UNAVAILABLE",rationaleCodes:["INPUT_NOT_READY","RADAR_COVERAGE_INSUFFICIENT"],asOf:{}};result=ledger.appendObservations(ledgerPath,payload({normalizedInput:unavailable("009815","RADAR_COVERAGE_INSUFFICIENT"),policyResult:unavailablePolicy,tradingDate:"2026-08-25",observedAt:"2026-08-25T14:00:00+08:00"}));const unavailableRow=result.results[0].record;assert.equal(unavailableRow.status,"DATA_UNAVAILABLE");assert.equal(Object.hasOwn(unavailableRow,"market"),false);assert.ok(unavailableRow.rationaleCodes.includes("RADAR_COVERAGE_INSUFFICIENT"));assert.equal(JSON.stringify(ledger.readLedger(ledgerPath).records[0]),before,"existing rows never mutate");
  for(const [symbol,reason] of [["0050","TARGET_ALLOCATION_MISSING"],["0050","PORTFOLIO_QUOTE_STALE"],["009815","RADAR_COVERAGE_INSUFFICIENT"]]){const date=symbol==="009815"?"2026-08-28":reason==="TARGET_ALLOCATION_MISSING"?"2026-08-26":"2026-08-27";const p={version:"PERSONAL_CAPITAL_POLICY_V1",symbol,status:"DATA_UNAVAILABLE",rationaleCodes:["INPUT_NOT_READY",reason],asOf:{}};assert.equal(ledger.appendObservations(ledgerPath,payload({normalizedInput:unavailable(symbol,reason),policyResult:p,tradingDate:date,observedAt:`${date}T14:00:00+08:00`})).appended,1);}
  for(const symbol of ledger.EXCLUDED_SYMBOLS)assert.throws(()=>ledger.buildRecord({normalizedInput:ready(symbol),policyResult:policy(symbol),tradingDate:"2026-08-29",observedAt:"2026-08-29T14:00:00+08:00"},"2026-08-24T15:53:12.601Z"),/SYMBOL_OUT_OF_SCOPE/);
  const intraday=ready();intraday.asOf.decisionMode="INTRADAY";assert.equal(ledger.appendObservations(ledgerPath,payload({normalizedInput:intraday,policyResult:policy(),tradingDate:"2026-08-29",observedAt:"2026-08-29T14:00:00+08:00"})).results[0].status,"SKIPPED_INTRADAY");
  assert.throws(()=>ledger.appendObservations(ledgerPath,{...payload(),futureReturn:1}),/OUTCOME_FIELDS_FORBIDDEN/);
  assert.throws(()=>ledger.buildRecord({normalizedInput:ready("0050",70,"2026-08-23T16:00:00.000Z"),policyResult:policy(),tradingDate:"2026-08-23",observedAt:"2026-08-24T23:55:00+08:00"},"2026-08-24T15:53:12.601Z"),/OBSERVATION_BEFORE_FORWARD_START/);
  assert.throws(()=>ledger.buildRecord({normalizedInput:ready("0050",70,"2026-08-24T15:53:12.600Z"),policyResult:policy(),tradingDate:"2026-08-24",observedAt:"2026-08-24T23:55:00+08:00"},"2026-08-24T15:53:12.601Z"),/OBSERVATION_BEFORE_FORWARD_START/);
  assert.throws(()=>ledger.buildRecord({normalizedInput:{...ready(),asOf:{...ready().asOf,canonicalAsOfAt:undefined}},policyResult:policy(),tradingDate:"2026-08-24",observedAt:"2026-08-24T23:55:00+08:00"},"2026-08-24T15:53:12.601Z"),/CANONICAL_ASOF_TIMESTAMP_REQUIRED/);
  const broken=ledger.readLedger(ledgerPath);broken.records[0].recordHash="broken";write(broken.records);assert.throws(()=>ledger.appendObservations(ledgerPath,payload({tradingDate:"2026-08-30",observedAt:"2026-08-30T14:00:00+08:00"})),/LEDGER_CHAIN_INVALID/);
  const source=fs.readFileSync(require.resolve("../scripts/append_personal_capital_forward.js"),"utf8");assert.doesNotMatch(source,/calculateFinalCoreScore|calculatePortfolio|\.evaluate\(/,"no Core Score, portfolio valuation, or policy evaluation");assert.doesNotMatch(source,/setInterval|schedule|cron/i,"no scheduler");
  console.log("PASS personal-capital-forward-v1 focused tests");
}finally{fs.rmSync(temp,{recursive:true,force:true});}
