"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm");
const root=path.resolve(__dirname,".."),html=fs.readFileSync(path.join(root,"index.html"),"utf8"),css=fs.readFileSync(path.join(root,"formal-black-gold.css"),"utf8");
const phase6=html.slice(html.indexOf("function radarHistoryPhase6State"),html.indexOf("function buildRadarV2Card"));
const official=html.slice(html.indexOf("function officialArtifactCoreScoreHistory"),html.indexOf("function localCoreScoreHistory"));
const next=html.slice(html.indexOf("function radarOverviewNextLevel"),html.indexOf("function radarOverviewScoreDelta"));
assert.ok(phase6.startsWith("function")&&official.startsWith("function")&&next.startsWith("function"));
const contract=require(path.join(root,"hs-decision-layer-v1.js")),context={Number,Math,String,Map,Object,Array,window:{HSDecisionLayerV1:contract},LONG_RADAR_CODES:new Set(["0050","00662","00757","00830","00935","009815"]),LONG_TERM_CORE_SCORE_VERSION:"FINAL_CORE_WEIGHT_V1",HSFinalCoreProduction:require(path.join(root,"final-core-production.js")),isCompletedTradingDate:date=>/^\d{4}-\d{2}-\d{2}$/.test(date),esc:value=>String(value),finalizedCoreScoreHistoryArtifact:null,valuationDetailsHtml:()=>"",legacyComparisonHtml:()=>"",similarStatsHtml:()=>"",buyPlanHtml:()=>""};
vm.createContext(context);vm.runInContext(`${official}\n${next}\n${phase6}\nthis.api={state:radarHistoryPhase6State,render:radarHistoryPhase6Html,advanced:detailAdvancedHtml};`,context);
const dates=[];for(let day=new Date("2022-01-03T00:00:00Z");dates.length<1000;day.setUTCDate(day.getUTCDate()+1))if(day.getUTCDay()>0&&day.getUTCDay()<6)dates.push(day.toISOString().slice(0,10));
const scores=[...Array(820).fill(30),...Array(60).fill(45),...Array(56).fill(47),...Array(64).fill(50)];
for(let i=0;i<5;i++){[scores[820+i],scores[995+i]]=[scores[995+i],scores[820+i]]}
[scores[0],scores[994]]=[scores[994],scores[0]];
const make=(values=scores)=>({schema_version:1,core_score_version:"FINAL_CORE_WEIGHT_V1",snapshots:values.map((score,i)=>({date:dates[i],snapshot_type:"FINALIZED_CLOSE",finalized:true,rows:[{symbol:"00830",final_core_score:score,core_score_version:"FINAL_CORE_WEIGHT_V1",data_as_of:`${dates[i]}T13:30:00+08:00`,factors:{dd52:{raw:i===999?-21.28:i<90?-30:-5}}}]}))});
const artifact=make();context.finalizedCoreScoreHistoryArtifact=artifact;const item={id:"00830",historyStats:{sameEnvironment:null,allEnvironments:null}};
let state=context.api.state(item,artifact);
assert.equal(state.size,1000);assert.equal(state.percentile,88);assert.equal(state.levelDays,116);assert.ok(Math.abs(state.levelRate-11.6)<1e-9);assert.equal(state.next.nextThreshold,50);assert.equal(state.nextDays,64);assert.ok(Math.abs(state.nextRate-6.4)<1e-9);
assert.equal(state.dd52Percentile,91);assert.ok(Math.abs(state.current.dd52+21.28)<1e-9);assert.equal(state.lastEntry,dates[995]);assert.equal(state.streak,5);assert.equal(state.streakCensored,false);
const last252=scores.slice(-252),yearLevelDays=last252.filter(value=>value>=40&&value<50).length;
let yearTransitions=0;for(let i=748;i<scores.length;i++)if(scores[i]>=40&&scores[i]<50&&i>0&&!(scores[i-1]>=40&&scores[i-1]<50))yearTransitions++;
assert.equal(state.yearSize,252);assert.equal(state.yearDays,yearLevelDays);assert.equal(state.yearEntries,yearTransitions);
const rendered=context.api.render(item);for(const copy of ['data-radar-history-phase="6"',"P88","11.6%","6.4%","P91","5 日","樣本 1000 日"])assert.ok(rendered.includes(copy),copy);
assert.match(rendered,/歷史正式交易日中，分數不高於目前者占 88%（含同分）/);assert.match(rendered,/約 9% 的交易日回撤更深/);assert.doesNotMatch(rendered,/歷史後續|勝率|平均報酬|建議買進/);
const short={...artifact,snapshots:artifact.snapshots.slice(-87)};
context.finalizedCoreScoreHistoryArtifact=short;assert.equal(context.api.state(item,short).size,87);assert.match(context.api.render(item),/樣本較短，歷史位置僅供參考/);
const transitions=[39,42,45,48,35,42,45].map((value,i)=>({date:dates[i],snapshot_type:"FINALIZED_CLOSE",finalized:true,rows:[{symbol:"00830",final_core_score:value,core_score_version:"FINAL_CORE_WEIGHT_V1",data_as_of:`${dates[i]}T13:30:00+08:00`,factors:{dd52:{raw:-5}}}]}));
let small=context.api.state(item,{...artifact,snapshots:transitions});assert.equal(small.yearEntries,2);assert.equal(small.lastEntry,dates[5]);assert.equal(small.streak,2);
const high=make([...scores.slice(0,-1),90]);small=context.api.state(item,high);assert.equal(small.next.isMaxLevel,true);context.finalizedCoreScoreHistoryArtifact=high;assert.match(context.api.render(item),/已進入最高級別/);assert.doesNotMatch(context.api.render(item),/歷史達到率/);
assert.equal(context.api.state({id:"009815"},artifact).kind,"WAIT_NATIVE");context.finalizedCoreScoreHistoryArtifact=artifact;assert.match(context.api.render({id:"009815"}),/正式歷史資料暫缺/);assert.equal(context.api.render({id:"00631L"}),"");
const provisional={...artifact,snapshots:[...artifact.snapshots,{...artifact.snapshots.at(-1),date:"2099-01-01",snapshot_type:"INTRADAY_CORE",finalized:false}]};assert.equal(context.api.state(item,provisional).size,1000);
const noD={...artifact,snapshots:artifact.snapshots.map((s,i)=>i===999?{...s,rows:[{...s.rows[0],factors:{}}]}:s)};assert.equal(context.api.state(item,noD).kind,"UNAVAILABLE");
assert.match(css,/\.radarHistoryPhase6\{/);assert.match(css,/@media\(max-width:390px\)\{\.radarHistoryP6Line/);assert.match(html,/formal-black-gold\.css\?v=20260918-radar-phase6-history-v1/);
console.log("PASS ETF Radar Phase 6 percentile, tier frequency, threshold rarity, DD52 depth, transitions, short sample, finalized-only and responsive guards");
