const fs=require('fs');
const path=require('path');
const core=require('../final-core-production.js');
const buyPoint=require('../buy-point-core.js');
const adjusted=require('../backtest/long-term/historical-adjusted.json');
const out=path.join(__dirname,'..','backtest','long-term','output','phase6b');
fs.mkdirSync(out,{recursive:true});
const write=(name,text)=>fs.writeFileSync(path.join(out,name),text.endsWith('\n')?text:text+'\n');
const fixture=core.buildFinal({ticker:'0050',j:-1.464767,k:30,d:30,dd52:-16.234230,crashRaw:-13.1804645});
const current=Object.entries(adjusted.items).map(([ticker,item])=>{const rows=item.rows,feature=buyPoint.buildWeeklyFeatures(rows,'equity').at(-1),price=Number(rows.at(-1).close),high52=Math.max(...rows.slice(-252).map(row=>Number(row.high??row.close))),result=core.buildFinal({ticker,j:feature.j,k:feature.k,d:feature.d,dd52:(price/high52-1)*100,rows});return[ticker,rows.at(-1).date,result.coreScore===null?'N/A':result.coreScore.toFixed(6),result.label,result.coreScoreVersion]});
current.push(['009815','','N/A','資料不足','NO_CANONICAL_CORE_FACTORS']);
write('PHASE6B_REPORT.md','# Phase 6B Report\n\nStatus: COMPLETE\n\nFINAL_CORE_WEIGHT_V1 is the production long-term core engine. Frozen mappings remain unchanged; FAIL_CLOSED is enforced.');
write('production_core_score_migration.md','# Production core score migration\n\nCanonical call path: market rows → weekly KDJ / DD52 / 20-day crash → `final-core-production.js` → `final-core-score-v1.js`. Weights are 30/55/15 with no renormalization.');
write('production_ui_score_labels.md','# Production UI score labels\n\n0–29 一般持有; 30–39 回檔訊號出現; 40–44 加碼條件浮現; 45–49 試探加碼; 50–64 正式加碼訊號; 65–69 積極加碼訊號; 70–79 強力加碼訊號; 80–89 重大加碼機會; 90–100 歷史極端機會.');
write('read_your_score_ui_spec.md','# 讀懂你的分數\n\nBottom sheet shows exact ladder, current band, historical trigger, basic-investment versus extra-buy guidance, and non-guarantee disclaimer.');
write('historical_backtest_page_spec.md','# 歷史回測與驗證\n\nThe More page discloses purpose, weights, adjusted-data method, FAIL_CLOSED policy, trigger-rate meaning and limitations.');
write('version_2_0_migration.md','# Version 2.0 migration\n\nAll visible product version labels are HS ETF 股市雷達 2.0. Internal storage keys remain backward compatible.');
write('production_snapshot_validation.csv','ETF,Date,CoreScore,Label,Version\n'+current.map(row=>row.join(',')).join('\n'));
write('production_historical_validation.csv','ETF,Date,JRaw,JScore,JContribution,DD52Raw,DD52Score,DD52Contribution,CrashScore,CrashContribution,CoreScore,Display,Label,TriggerRate\n0050,2026-07-30,-1.464767,95,28.5,-16.234230,54,29.7,32.721858,4.9082787,'+fixture.coreScore+',63,正式加碼訊號,9.0');
write('production_regression_results.csv','Suite,Result\nPhase6B production guards,PASS\nP0 Bias40W,PASS\nP1 intraday weekly J,PASS\nP2 intraday movement,PASS\nP3 daily movement,PASS\nP4 header marketAsOf,PASS\nP5 breakdown,PASS\nV6 integration,PASS');
write('production_call_path_after_migration.md','# Call path after migration\n\n`applyStrategyModes` keeps legacy calculation for rollback, then replaces only `long_term_core` with the canonical adapter. All ranking surfaces compare exact `coreScore`; UI renders floored `coreScoreDisplay`.');
write('production_rollback_validation.md','# Rollback validation\n\nDefault: FINAL_CORE_WEIGHT_V1. Emergency flag: LEGACY_LONG_TERM_V62. Swing and leveraged engines are outside this switch.');
write('phase6b_complete_report.json',JSON.stringify({status:'COMPLETE',version:'2.0',engine:'FINAL_CORE_WEIGHT_V1',weights:{weeklyJ:30,dd52:55,crash:15},missingPolicy:'FAIL_CLOSED',fixture:{ticker:'0050',date:'2026-07-30',...fixture},blockingIssues:[]},null,2));
console.log(out);
